Repository kubernetes/ingress-gce, pull requests merged in 2018-12, with the labels that each got.

#547 do not leak LB when ingress class is changed
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#571 Add masterupgrading flag
  cmd/e2e-test/upgrade_test.go
  pkg/e2e/sandbox.go
  pkg/e2e/status.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#552 Fix wrong filtering of ManagedCertificate objects.
  pkg/loadbalancers/certificates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#551 Fix wrong filtering of ManagedCertificate objects.
  pkg/loadbalancers/certificates.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#573 Fixed misspell (annotation name) i README.md
  examples/static-ip/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#558 Initialize directories which will house our updated documentation.
  docs/concepts/README.md
  docs/contrib/README.md
  docs/deploy/README.md
  docs/dev/README.md
  docs/dev/testing.md
  docs/troubleshooting/README.md
  docs/troubleshooting/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#570 Create task queues with a name so that usage metrics can be tracked by Prometheus
  pkg/controller/controller.go
  pkg/controller/node.go
  pkg/firewalls/controller.go
  pkg/utils/taskqueue.go
  pkg/utils/taskqueue_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#575 Increase deletion timeout for e2e tests
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#577 Ingress e2e test cleanup
  cmd/e2e-test/upgrade_test.go
  pkg/e2e/status.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#579 add a flag to control neg syncer type
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#581 fix a bug where transaction neg syncer will miss neg retry
  pkg/neg/manager.go
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#580 remove loop from flush(). start/stop informers depending on k8s master
  pkg/e2e/status.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#585 Revert "Remove unused named ports from instance group's"
  pkg/instances/instances.go
  pkg/instances/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#582 reflect readiness probe in health check for NEG enabled ClusterIP service backend
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#592 [E2E] In run.sh, add option to disable the resource dump at the end of the test.
  cmd/e2e-test/run.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#588 Upgrade Test: Ignore connection refused errors when WaitForIngress() is called.
  cmd/e2e-test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
