Repository kubernetes/ingress-gce, pull requests merged in 2018-04, with the labels that each got.

#146 Ingress HTTP/2 Support
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/fakes.go
  pkg/backends/interfaces.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/instances/fakes.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: cncf-cla: yes, lgtm, size/XL

#187 Cherry-pick checkpoint changes to 1.0
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
Labels: cncf-cla: yes, lgtm, size/L

#188 Add some documentation on post-release TODO's
  docs/dev/post-release-steps.md
Labels: cncf-cla: yes, lgtm, size/M

#190 Update glbc manifest to v1.0.1
  deploy/glbc/yaml/glbc.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#191 Small changes to deploy/glbc/README
  deploy/glbc/README.md
Labels: cncf-cla: yes, lgtm, size/S

#189 Satisfy golang 1.10 vetting
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#192 Bump golang build image to 1.10
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#198 Ensure .go/cache in build
  build/rules.mk
Labels: cncf-cla: yes, lgtm, size/XS

#199 Ensure only needed nodeports on instance group on ingress sync
  pkg/controller/controller.go
  pkg/controller/translator/translator.go
Labels: cncf-cla: yes, lgtm, size/S

#200 Change naming of SSL certs
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#206 Remove duplicate nodeport translation
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS

#205 Start changelog file
  CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/M

#202 Vendor in Cluster Registry code
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/defaults.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/doc.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/generated.pb.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/generated.proto
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/register.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/types.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/validation/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/validation/validation.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/validation/validation_test.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/zz_generated.defaults.go
  vendor/k8s.io/cluster-registry/pkg/apis/clusterregistry/v1alpha1/zz_generated.openapi.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/clientset.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/doc.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/fake/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/fake/clientset_generated.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/fake/doc.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/fake/register.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/scheme/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/scheme/doc.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/scheme/register.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/clusterregistry_client.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/doc.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/fake/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/fake/doc.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/fake/fake_cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/fake/fake_clusterregistry_client.go
  vendor/k8s.io/cluster-registry/pkg/client/clientset_generated/clientset/typed/clusterregistry/v1alpha1/generated_expansion.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/interface.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/interface.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/factory.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/generic.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/internalinterfaces/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/expansion_generated.go
Labels: cncf-cla: yes, lgtm, size/XXL

#207 Refactor translator.ToURLMap to not re-fetch backend services
  cmd/glbc/app/namer.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/gceurlmap.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/L

#210 Update post-release-steps.md
  docs/dev/post-release-steps.md
Labels: cncf-cla: yes, lgtm, size/XS

#212 Add multi-cluster flag
  pkg/flags/flags.go
Labels: cncf-cla: yes, size/XS

#211 Split sync up
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/utils/taskqueue.go
Labels: cncf-cla: yes, lgtm, size/M

#213 Fix multiple secrets with same certificate
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: cncf-cla: yes, lgtm, size/M

#217 Bootstrap multi-cluster controller
  Gopkg.lock
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator_test.go
  pkg/mci/controller.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncer_test.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/clusterregistry/v1alpha1/interface.go
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/internalinterfaces/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/informers_generated/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/BUILD.bazel
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/cluster.go
  vendor/k8s.io/cluster-registry/pkg/client/listers_generated/clusterregistry/v1alpha1/expansion_generated.go
Labels: cncf-cla: yes, size/L

#214 Code to setup removal of ServicePort logic out of translator
  Gopkg.lock
  Gopkg.toml
  pkg/backends/utils.go
  pkg/backends/utils_test.go
  pkg/controller/utils.go
  pkg/mapper/fakes.go
  pkg/mapper/interfaces.go
  pkg/mapper/mapper.go
  pkg/mapper/mapper_test.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
Labels: cncf-cla: yes, lgtm, size/XXL

#218 Set glog levels in loadbalancer pool & fix markdown
  BETA_LIMITATIONS.md
  README.md
  deploy/glbc/README.md
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
Labels: cncf-cla: yes, lgtm, size/M

#216 Cherrypick: Fix multiple secrets with same certificate
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: cncf-cla: yes, lgtm, size/M

#221 Update annotations.md
  docs/annotations.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#224 Update changelog for 1.1.1
  CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/XS

#225 Remove dead code for e2e testing. We do all e2e testing through k/k now
  build/e2e-internal/e2e-down.sh
  build/e2e-internal/e2e-env.sh
  build/e2e-internal/e2e-status.sh
  build/e2e-internal/e2e-up.sh
  build/e2e-internal/ginkgo-e2e.sh
  build/e2e.go
Labels: cncf-cla: yes, lgtm, size/L

#228 Bump glbc.yaml to 1.1.1
  deploy/glbc/yaml/glbc.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#226 Add support for logging latest commit hash of GLBC build being used
  Makefile
  build/build.sh
  build/rules.mk
  cmd/glbc/main.go
  pkg/version/version.go
Labels: cncf-cla: yes, lgtm, size/S

#223 Integrate ClusterServiceMapper into translator.
  pkg/backends/utils.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/errors/errors.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/mapper/mapper.go
  pkg/mapper/mapper_test.go
  pkg/test/manifests/ing1.yaml
  pkg/test/utils.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/XL

#230 Add support for logging latest commit hash of GLBC build being used
  Makefile
  build/build.sh
  build/rules.mk
  cmd/glbc/main.go
  pkg/version/version.go
Labels: cncf-cla: yes, lgtm, size/S

#231 Add support for logging latest commit hash of GLBC build being used
  Makefile
  build/build.sh
  build/rules.mk
  cmd/glbc/main.go
  pkg/version/version.go
Labels: cncf-cla: yes, lgtm, size/S

#232 Add support for logging latest commit hash of GLBC build being used
  Makefile
  build/build.sh
  build/rules.mk
  cmd/glbc/main.go
  pkg/version/version.go
Labels: cncf-cla: yes, lgtm, size/S

#234 Add ability for MCI controller to enqueue ingresses
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/mci/controller.go
Labels: cncf-cla: yes, lgtm, size/M

#235 Small addition to ClusterServiceMapper interface
  pkg/mapper/fakes.go
  pkg/mapper/interfaces.go
  pkg/mapper/mapper.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/M

#233 First pass at an interface to manage informers
  pkg/informer/informer.go
  pkg/informer/interfaces.go
Labels: cncf-cla: yes, lgtm, size/L

#236 Add code for building cluster client and other resources.
  pkg/context/context.go
  pkg/mci/controller.go
Labels: cncf-cla: yes, lgtm, size/M

#237 Add an interface to manage target resources
  pkg/target/interfaces.go
  pkg/target/target.go
  pkg/target/utils.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/L

#238 Final changes to make MCI controller work
  cmd/glbc/main.go
  pkg/annotations/ingress.go
  pkg/backends/backends.go
  pkg/context/context.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/controller/utils_test.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
  pkg/firewalls/interfaces.go
  pkg/informer/informer.go
  pkg/mci/controller.go
  pkg/mci/utils.go
  pkg/target/interfaces.go
  pkg/target/target.go
  pkg/target/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/XL
