Repository kubernetes/ingress-gce, pull requests merged in 2018-07, with the labels that each got.

#381 Some fixes for 1.2
  cmd/glbc/main.go
  pkg/controller/controller.go
  pkg/controller/utils.go
  pkg/neg/controller.go
  pkg/neg/syncer.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M

#386 Increase timeout on waiting for GLBC resource deletion
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, size/XS

#387 Modify security policy e2e test to create unique GCP resources.
  cmd/e2e-test/security_policy_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#383 Add more negative test cases for backend config
  cmd/e2e-test/backend_config_test.go
  pkg/backendconfig/backendconfig.go
Labels: cncf-cla: yes, lgtm, size/L

#389 Cherrypick #381and #384 into release-1.2
  cmd/glbc/main.go
  pkg/backends/backends_test.go
  pkg/backends/features/doc.go
  pkg/backends/features/features.go
  pkg/backends/features/features_test.go
  pkg/controller/controller.go
  pkg/controller/utils.go
  pkg/neg/controller.go
  pkg/neg/syncer.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/L

#390 Cherrypick #383: Unmask get backend config errors
  pkg/backendconfig/backendconfig.go
Labels: cncf-cla: yes, lgtm, size/XS

#393 Implement security policy validator for real
  pkg/fuzz/features/security_policy.go
  pkg/fuzz/helpers.go
Labels: cncf-cla: yes, lgtm, size/M

#394 Documentation fixes
  README.md
  examples/deployment/gce-ingress-controller.yaml
  examples/multi-path/gce-multi-path-ingress.yaml
  examples/multi-path/svc.yaml
Labels: cncf-cla: yes, lgtm, size/L

#374 Typo in message: SyncNetworkEndpiontGroupFailed->SyncNetworkEndpointGroupFailed
  pkg/neg/syncer.go
Labels: cncf-cla: yes, lgtm, size/XS

#398 Remove error return value from controller initialization
  cmd/glbc/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/S

#401 Pace operation polling
  cmd/glbc/app/clients.go
  pkg/flags/flags.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
Labels: cncf-cla: yes, lgtm, size/M

#405 Introduce ControllerContextConfig and move some command-line tunable stuff there
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/controller/translator/translator_test.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncer_test.go
Labels: cncf-cla: yes, lgtm, size/L

#406 Remove EnsureLB from ClusterManager
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/S

#356 URLMap sync
  pkg/controller/controller.go
  pkg/controller/translator/testdata/ingress-missing-multi-svc.json
  pkg/controller/translator/testdata/ingress-missing-rule-svc.json
  pkg/controller/translator/testdata/ingress-multi-empty.json
  pkg/controller/translator/testdata/ingress-multi-paths.json
  pkg/controller/translator/testdata/ingress-no-host.json
  pkg/controller/translator/testdata/ingress-single-host.json
  pkg/controller/translator/testdata/ingress-two-hosts.json
  pkg/controller/translator/translator_test.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/utils/gceurlmap.go
  pkg/utils/gceurlmap_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/XXL

#407 cherrypick #402 to release-1.2 branch
  pkg/controller/utils.go
  pkg/controller/utils_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/L

#408 Raw patch to cloud provider to fix operations issue
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/BUILD
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/errors.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/op.go
Labels: cncf-cla: yes, lgtm, size/M

#409 Cherry pick on release-1.2 for #408
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/BUILD
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/errors.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/cloud/op.go
Labels: cncf-cla: yes, lgtm, size/M

#411 Fix issue with yaml in glbc deploy/
  deploy/glbc/yaml/rbac.yaml
Labels: cncf-cla: yes, lgtm, size/XS

#412 Bump timeout in tests to match reality
  cmd/e2e-test/backend_config_test.go
  cmd/e2e-test/security_policy_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#413 Rename context's hcLock to lock
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/S

#414 unit test: add locking when read from shared map
  pkg/backends/features/securitypolicy_test.go
Labels: cncf-cla: yes, lgtm, size/S

#415 Expose newIndexer in pkg/context
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/S

#416 Add doc link for backend config
  docs/annotations.md
Labels: cncf-cla: yes, lgtm, size/XS
