Repository kubernetes/ingress-gce, pull requests merged in 2018-08, with the labels that each got.

#420 Move joiner methods into context
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/firewalls/controller.go
  pkg/utils/join.go
Labels: cncf-cla: yes, lgtm, size/L

#421 Remove EnsureInstanceGroupsAndPorts wrapper func
  pkg/controller/cluster_manager.go
  pkg/instances/utils.go
Labels: cncf-cla: yes, lgtm, size/S

#370 Align node filtering with kubernetes service controller
  pkg/controller/translator/translator.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/M

#423 export TrimFieldsEvenly
  pkg/utils/namer.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XS

#422 Refactor to remove ClusterManager completely
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/controller/node.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils_test.go
  pkg/firewalls/controller.go
  pkg/firewalls/controller_test.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncer_test.go
Labels: cncf-cla: yes, size/XL

#425 Push dependency on the GCECloud up out of the neg controller
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/neg/cloudprovideradapter.go
  pkg/neg/controller.go
  pkg/neg/fakes.go
  pkg/neg/interfaces.go
  pkg/neg/manager.go
  pkg/neg/syncer.go
Labels: cncf-cla: yes, lgtm, size/L

#429 move NewIndexer to utils
  pkg/context/context.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/S

#417 Introduce cloud.google.com/app-protocols to eventually replace existing annotation
  pkg/annotations/service.go
  pkg/annotations/service_test.go
Labels: cncf-cla: yes, lgtm, size/M

#424 Extract BackendPool interface into three 3 separate interfaces
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/ig_linker.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/interfaces.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/loadbalancers/l7.go
  pkg/utils/description.go
Labels: cncf-cla: yes, lgtm, size/XXL

#431 Fix bug in backend syncer where backend service was being created without health check
  pkg/backends/backends.go
  pkg/backends/ig_linker_test.go
  pkg/backends/interfaces.go
  pkg/backends/neg_linker_test.go
  pkg/backends/syncer.go
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/M

#434 Fix null-pointer exception in url map ensure logic
  pkg/loadbalancers/url_maps.go
Labels: cncf-cla: yes, lgtm, size/XS

#432 Add a version mapping for both GCE and GKE clusters
  README.md
Labels: cncf-cla: yes, size/S

#391 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS

#435 BackendPool Update() should set backend service version
  pkg/backends/backends.go
  pkg/backends/syncer.go
Labels: cncf-cla: yes, lgtm, size/XS

#436 Fix error handling in controller sync()
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS

#437 Add myself to OWNERS so I can do a release.
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#439 Cherry-pick necessary commits for v1.3.0 release.
  cmd/glbc/main.go
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/backends/backends_test.go
  pkg/backends/features/features.go
  pkg/backends/features/features_test.go
  pkg/context/context.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/controller/node.go
  pkg/controller/translator/testdata/ingress-missing-multi-svc.json
  pkg/controller/translator/testdata/ingress-missing-rule-svc.json
  pkg/controller/translator/testdata/ingress-multi-empty.json
  pkg/controller/translator/testdata/ingress-multi-paths.json
  pkg/controller/translator/testdata/ingress-no-host.json
  pkg/controller/translator/testdata/ingress-single-host.json
  pkg/controller/translator/testdata/ingress-two-hosts.json
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/controller/utils_test.go
  pkg/firewalls/controller.go
  pkg/firewalls/controller_test.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
  pkg/firewalls/interfaces.go
  pkg/healthchecks/healthchecks.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncer_test.go
  pkg/test/utils.go
  pkg/utils/gceurlmap.go
  pkg/utils/gceurlmap_test.go
  pkg/utils/join.go
  pkg/utils/serviceport.go
  pkg/utils/taskqueue.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/XXL

#441 Fix main controller health check
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS

#442 Remove 'Description' and 'Required' from OpenAPI schema root layer
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/XS

#430 Remove unused named ports from instance group's
  pkg/instances/instances.go
  pkg/instances/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#443 Move NegStatus and PortNameMap to pkg/neg/types
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/interfaces.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#444 Cherrypick #442 into release-1.3
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#440 do not create instance group with NEG backends
  pkg/controller/controller.go
  pkg/controller/utils.go
  pkg/controller/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#446 Add some utility functions to support finalizers
  Gopkg.lock
  pkg/utils/finalizer.go
  pkg/utils/finalizer_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/kubernetes/pkg/util/slice/BUILD
  vendor/k8s.io/kubernetes/pkg/util/slice/slice.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#447 Export getPatchBytes in pkg/util
  pkg/utils/finalizer.go
  pkg/utils/finalizer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#428 Introduce a new interface to encapsulate Ingress sync and controller implementation of the sync
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#448 Slight refactor of Controller interface to eliminate Ingress type specifically
  pkg/controller/controller.go
  pkg/controller/types.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#449 Move joinErrs() to utils and export it
  pkg/controller/controller.go
  pkg/controller/utils.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#450 deflake TestGetNodePortsUsedByIngress unit test
  pkg/controller/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#452 fix and refactor on NEG annotation handling
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/controller/translator/translator.go
  pkg/neg/controller.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#453 Add JSONMerge patch utilities and move some files around
  Gopkg.lock
  pkg/utils/finalizer.go
  pkg/utils/finalizer_test.go
  pkg/utils/patch.go
  pkg/utils/patch_test.go
  vendor/github.com/evanphx/json-patch/.travis.yml
  vendor/github.com/evanphx/json-patch/LICENSE
  vendor/github.com/evanphx/json-patch/README.md
  vendor/github.com/evanphx/json-patch/merge.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#455 Remove JSONMergePatch util
  pkg/utils/patch.go
  pkg/utils/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#456 NEG controller bug fix
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#457 Cherrypick #456 into release-1.3
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#462 Cherrypick #461 into release 1.3
  pkg/controller/controller.go
  pkg/neg/controller.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
