Repository kubernetes/ingress-gce, pull requests merged in 2018-05, with the labels that each got.

#247 Add util functions for backendConfig annotation
  pkg/annotations/service.go
  pkg/annotations/service_test.go
Labels: cncf-cla: yes, lgtm, size/L

#256 Minor cleanup to docs and examples
  README.md
  docs/annotations.md
  docs/faq/gce.md
  docs/testing.md
  examples/https/Makefile
  examples/https/README.md
  examples/static-ip/README.md
  examples/static-ip/gce-static-ip-ingress.yaml
  pkg/backends/backends.go
  pkg/healthchecks/healthchecks.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/neg/controller_test.go
  pkg/neg/syncer.go
  pkg/ratelimit/ratelimit_test.go
Labels: cncf-cla: yes, lgtm, size/L

#254 Refactor gceurlmap to a struct representation
  pkg/backends/fakes.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/gceurlmap.go
  pkg/utils/gceurlmap_test.go
  pkg/utils/namer.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/L

#257 Merge the logic of ToUrlMap() and IngressToNodePorts() [WIP]
  cmd/glbc/app/init.go
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/fakes.go
  pkg/backends/interfaces.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/gceurlmap.go
  pkg/utils/gceurlmap_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/XL

#260 Update healthcheck docs regarding containerPort
  examples/health-checks/README.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#252 Add utils for retrieving backendconfigs for service (and reversely)
  pkg/backendconfig/backendconfig.go
  pkg/backendconfig/backendconfig_test.go
Labels: cncf-cla: yes, lgtm, size/L

#266 Small aesthetic fixes to code base.
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/ratelimit/ratelimit_test.go
Labels: cncf-cla: yes, lgtm, size/L

#265 Introduce configuration for IAP & CDN into BackendConfig spec
  pkg/apis/backendconfig/v1alpha1/types.go
Labels: cncf-cla: yes, lgtm, size/M

#262 BackendService naming for NEG backend services & healthchecks
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/fakes.go
  pkg/backends/interfaces.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecks/interfaces.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/utils/namer.go
  pkg/utils/namer_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/XL

#264 Condense health checkers into one health checker for all backends.
  cmd/glbc/main.go
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/flags/flags.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecks/interfaces.go
Labels: cncf-cla: yes, lgtm, size/L

#270 Pass service/port tuple separate from ServicePort
  cmd/glbc/app/init.go
  cmd/glbc/main.go
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/fakes.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/flags/flags.go
  pkg/healthchecks/healthchecks.go
  pkg/utils/serviceport.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/L

#273 Fix BackendConfigKey to use beta
  pkg/annotations/service.go
Labels: cncf-cla: yes, lgtm, size/XS

#275 TranslateIngress changes
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/errors/errors.go
  pkg/controller/translator/testdata/ingress-missing-multi-svc.json
  pkg/controller/translator/testdata/ingress-missing-multi-svc.yaml
  pkg/controller/translator/testdata/ingress-missing-rule-svc.json
  pkg/controller/translator/testdata/ingress-missing-rule-svc.yaml
  pkg/controller/translator/testdata/ingress-multi-empty.json
  pkg/controller/translator/testdata/ingress-multi-empty.yaml
  pkg/controller/translator/testdata/ingress-multi-paths.json
  pkg/controller/translator/testdata/ingress-multi-paths.yaml
  pkg/controller/translator/testdata/ingress-no-host.json
  pkg/controller/translator/testdata/ingress-no-host.yaml
  pkg/controller/translator/testdata/ingress-single-host.json
  pkg/controller/translator/testdata/ingress-single-host.yaml
  pkg/controller/translator/testdata/ingress-two-hosts.json
  pkg/controller/translator/testdata/ingress-two-hosts.yaml
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/neg/fakes.go
  pkg/test/utils.go
  pkg/utils/gceurlmap.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/XXL

#279 Ensure Load Balancer using IG links instead of IG compute object
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/interfaces.go
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/M

#276 fake backendservices save alpha objects by default
  pkg/backends/backends_test.go
  pkg/backends/fakes.go
  pkg/controller/fakes.go
Labels: cncf-cla: yes, lgtm, size/L

#278 Update documentation to include multiple-TLS support.
  README.md
Labels: cncf-cla: yes, lgtm, size/M

#283 Make sure structs in OpenAPI spec are serialized with 'type: object'
  pkg/crd/validation.go
Labels: cncf-cla: yes, lgtm, size/XS

#285 Bake backend config into ServicePort
  pkg/controller/controller.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, lgtm, size/L

#281 Define security policy API in BackendConfig
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/M

#267 Fix typo in faq
  docs/faq/gce.md
Labels: cncf-cla: yes, size/XS

#289 Add custom validation for BackendConfig + hook validation into Translator
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/backendconfig/validation.go
  pkg/backendconfig/validation_test.go
  pkg/context/context.go
  pkg/controller/errors/errors.go
  pkg/controller/translator/translator.go
Labels: cncf-cla: yes, lgtm, size/L

#287 Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: cncf-cla: yes, lgtm, size/S

#288 Fix bug with ensuring BackendService settings + health checks
  pkg/backends/backends.go
  pkg/backends/backends_test.go
Labels: cncf-cla: yes, lgtm, size/M
