Repository kubernetes/ingress-gce, pull requests merged in 2018-03, with the labels that each got.

#144 Adding information about using GCP SSL certs for frontend HTTPS
  README.md
Labels: cncf-cla: yes, lgtm, size/S

#147 update: s_k/ingress-k/ingress-gce_ in annotations.md
  docs/annotations.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#150 Cleanup some unused files
  ingress-app.yaml
  rc.yaml
  tests/manifests/configuration-a.json
  tests/manifests/configuration-b.json
  tests/manifests/configuration-c.json
Labels: cncf-cla: yes, lgtm, size/XXL

#140 Add instructions and a tool for people who want to try out a new version of the ingress controller before it is released.
  README.md
  deploy/glbc/README.md
  deploy/glbc/gce.conf
  deploy/glbc/script.sh
  deploy/glbc/yaml/default-http-backend.yaml
  deploy/glbc/yaml/glbc.yaml
  deploy/glbc/yaml/rbac.yaml
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/XL

#151 Fix copyright in deploy/glbc/script.sh
  deploy/glbc/script.sh
Labels: cncf-cla: yes, lgtm, size/S

#148 Initial implementation for ingress rate limiting
  cmd/glbc/app/clients.go
  pkg/flags/flags.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
  vendor/k8s.io/kubernetes/pkg/cloudprovider/providers/gce/gce.go
Labels: cncf-cla: yes, lgtm, size/L

#153 Fix formatting error in docs/README.md
  docs/README.md
Labels: cncf-cla: yes, lgtm, size/M

#165 Adding ListUrlMaps to LoadBalancers interface
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/interfaces.go
Labels: cncf-cla: yes, lgtm, size/XS

#168 Update testing.md
  docs/testing.md
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#169 Use given name rather than regenerating it in UrlMap fake
  pkg/loadbalancers/fakes.go
Labels: cncf-cla: yes, lgtm, size/XS

#170 Checkpoint() takes a single LB rather than a list of LBs
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/S

#177 Minor spelling and capitalization changes
  BETA_LIMITATIONS.md
  README.md
  docs/admin.md
  docs/annotations.md
  docs/catalog.md
  docs/dev/README.md
  docs/dev/custom-controller.md
  docs/dev/getting-started.md
  docs/dev/setup-cluster.md
  docs/faq/README.md
  docs/faq/gce.md
  docs/testing.md
  docs/troubleshooting.md
  examples/deployment/README.md
  examples/tls-termination/README.md
  examples/websocket/README.md
  pkg/tls/tls.go
Labels: cncf-cla: yes, lgtm, size/L

#178 Updating FakeLoadBalancers.Delete to return NotFound when appropriate
  pkg/loadbalancers/fakes.go
Labels: cncf-cla: yes, lgtm, size/S

#180 Fix path default-http-backend.yaml
  deploy/glbc/script.sh
Labels: cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#183 Fix sync of multi-cluster ingress
  pkg/controller/cluster_manager.go
  pkg/controller/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
Labels: cncf-cla: yes, lgtm, size/L
