Repository kubernetes/ingress-gce, pull requests merged in 2018-11, with the labels that each got.

#506 Add annotation to suppress XPN firewall events
  pkg/annotations/ingress.go
  pkg/firewalls/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#531 Add gke.io/suppress-firewall-xpn-error annotation to suppress XPN firewall events
  pkg/annotations/ingress.go
  pkg/firewalls/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#527 e2e and fuzz tests for session affinity
  cmd/e2e-test/affinity_test.go
  pkg/fuzz/features/affinity.go
  pkg/fuzz/features/features.go
  pkg/fuzz/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#533 README.md: don't assume instance groups where NEG is an option
  README.md
  docs/annotations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#499 Add a Backofff Handler utils
  pkg/neg/syncers/backoff.go
  pkg/neg/syncers/backoff_test.go
  pkg/neg/syncers/retry_handler.go
  pkg/neg/syncers/retry_handler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#503 Welcome defaultbackend to the ingress-gce repo
  Dockerfile.404-server
  Makefile
  cmd/404-server/README.md
  cmd/404-server/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#521 e2e tests for timeout and draining timeout
  cmd/e2e-test/draining_test.go
  cmd/e2e-test/timeout_test.go
  pkg/fuzz/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#532 Transaction Syncer
  pkg/neg/syncers/batch.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#548 Connection Draining E2E: Fix test log message level
  cmd/e2e-test/draining_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#517 Add pkg/common/operator & pkg/common/typed to make resource joins much cleaner.
  pkg/backendconfig/backendconfig.go
  pkg/backendconfig/backendconfig_test.go
  pkg/backendconfig/utils.go
  pkg/common/operator/backendconfig.go
  pkg/common/operator/backendconfig_test.go
  pkg/common/operator/doc.go
  pkg/common/operator/ingress.go
  pkg/common/operator/ingress_test.go
  pkg/common/operator/service.go
  pkg/common/operator/service_test.go
  pkg/common/typed/backendconfig.go
  pkg/common/typed/ingress.go
  pkg/common/typed/service.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/firewalls/controller.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#546 Ingress Upgrade Testing
  cmd/e2e-test/affinity_test.go
  cmd/e2e-test/basic_test.go
  cmd/e2e-test/basic_upgrade_test.go
  cmd/e2e-test/cdn_test.go
  cmd/e2e-test/draining_test.go
  cmd/e2e-test/iap_test.go
  cmd/e2e-test/security_policy_test.go
  cmd/e2e-test/timeout_test.go
  pkg/e2e/framework.go
  pkg/e2e/helpers.go
  pkg/e2e/sandbox.go
  pkg/e2e/status.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#556 defaultbackend image now has the architecture in the image name
  README.md
  deploy/glbc/yaml/default-http-backend.yaml
  examples/deployment/gce-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#561 rename basic_upgrade -> upgrade
  cmd/e2e-test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
