Repository kubernetes/ingress-gce, pull requests merged in 2018-09, with the labels that each got.

#463 Support short names in CRD Meta. Allows for abbreviating CRD's in kubectl
  pkg/crd/crd.go
  pkg/crd/meta.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#451 Do not truncate tls certs based on target proxy limit
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/tls/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#464 Revert "Refactor some uses of snapshotter.Add() to use bool rather than real object"
  pkg/backends/backends.go
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#388 Fire warning event instead of hard failing if TLS certificate is not present
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#472 Cherrypick of #434 on release 1.3
  pkg/loadbalancers/url_maps.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#459 Harden NEG GC
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#473 Cherrypick #388 on release 1.3 branch
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#479 Replace kubernetes-users mailing list link with discuss forum link
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#491 Modify GroupKey type to contain group name + modify NEG linker to consider provided name
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/interfaces.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#489 Restructure NEG controller
  pkg/backends/neg_linker_test.go
  pkg/neg/cloudprovideradapter.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/metrics/metrics.go
  pkg/neg/syncer/batch.go
  pkg/neg/syncer/batch_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#494 include NEG naming scheme for NameBelongsToCluster
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#496 Update defaultbackend image to 1.5
  deploy/glbc/yaml/default-http-backend.yaml
  docs/troubleshooting.md
  examples/deployment/gce-ingress-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#504 Expose utils.hasFinalizer
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
