Repository kubernetes/ingress-gce, pull requests merged in 2018-10, with the labels that each got.

#505 Allow for setting the rate limiter on the work queue
  pkg/utils/taskqueue.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#484 Bump Alpine base image version
  Dockerfile.fuzzer
  Dockerfile.glbc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#502 Fix a potential nil pointer exception
  pkg/neg/syncer/batch.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#488 Use HTTPS readiness probe for HTTP2 services because the Kubernetes A…
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#482 add work queue to process endpoint changes
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#492 Restructure syncer package
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/batch.go
  pkg/neg/syncers/batch_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#501 merge negBelongsToCluster into IsNEG
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#519 Fix events-based e2e tests
  Gopkg.lock
  cmd/e2e-test/main_test.go
  cmd/fuzzer/app/validate.go
  cmd/fuzzer/fuzzer.go
  cmd/glbc/app/clients.go
  pkg/controller/controller.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#520 Update deploy/glbc yaml files for BackendConfig
  deploy/glbc/yaml/glbc.yaml
  deploy/glbc/yaml/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#522 [e2e test] append key value to resources instead of pointer
  pkg/fuzz/gcp.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#523 In e2e tests, always skip checking for deletion of default backend service
  cmd/e2e-test/basic_test.go
  cmd/e2e-test/cdn_test.go
  cmd/e2e-test/iap_test.go
  cmd/e2e-test/security_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#524 Add an example for running specific test case to readme
  cmd/e2e-test/readme.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#365 Fix the issue where Shutdown doesn't shutdown taskqueue
  cmd/glbc/main.go
  pkg/controller/controller.go
  pkg/controller/node.go
  pkg/firewalls/controller.go
  pkg/utils/taskqueue.go
  pkg/utils/taskqueue_test.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/M

#529 Managed Certs integration: Fix code so that informers are not instantiated if managed certs is not enabled
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#530 Replace existing CHANGELOG.md with one generated via a script
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XL
