Repository kubernetes/ingress-gce, pull requests merged in 2019-05, with the labels that each got.

#741 Cherrypick #728 onto 1.5 branch.
  pkg/tls/tls.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#745 Adding docker configuration file for the 404-server-with-metrics and …
  Dockerfile.404-server-with-metrics
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#747 Adding the /healthz handler to the 404-default-server-with-metris to …
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#746 Update canonical rbac.yaml with latest, minimal bindings
  docs/deploy/resources/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#748 readiness reflector
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/interface.go
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/utils.go
  pkg/neg/syncers/batch.go
  pkg/neg/syncers/batch_test.go
  pkg/neg/syncers/syncer.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#756 Deploying to GKE self managed has invalid YAML
  docs/deploy/resources/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#753 Rebase of #559 "Scaffolding for FrontendConfig"
  cmd/glbc/main.go
  hack/update-codegen.sh
  pkg/annotations/ingress.go
  pkg/apis/frontendconfig/register.go
  pkg/apis/frontendconfig/v1beta1/doc.go
  pkg/apis/frontendconfig/v1beta1/register.go
  pkg/apis/frontendconfig/v1beta1/types.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
  pkg/common/operator/frontendconfig.go
  pkg/common/operator/frontendconfig_test.go
  pkg/common/operator/ingress.go
  pkg/common/typed/frontendconfig.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator_test.go
  pkg/firewalls/controller_test.go
  pkg/flags/flags.go
  pkg/frontendconfig/client/clientset/versioned/clientset.go
  pkg/frontendconfig/client/clientset/versioned/doc.go
  pkg/frontendconfig/client/clientset/versioned/fake/clientset_generated.go
  pkg/frontendconfig/client/clientset/versioned/fake/doc.go
  pkg/frontendconfig/client/clientset/versioned/fake/register.go
  pkg/frontendconfig/client/clientset/versioned/scheme/doc.go
  pkg/frontendconfig/client/clientset/versioned/scheme/register.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/doc.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/doc.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/fake_frontendconfig.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/fake_frontendconfig_client.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/frontendconfig.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/frontendconfig_client.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/generated_expansion.go
  pkg/frontendconfig/client/informers/externalversions/factory.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/interface.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/v1beta1/frontendconfig.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/v1beta1/interface.go
  pkg/frontendconfig/client/informers/externalversions/generic.go
  pkg/frontendconfig/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/frontendconfig/client/listers/frontendconfig/v1beta1/expansion_generated.go
  pkg/frontendconfig/client/listers/frontendconfig/v1beta1/frontendconfig.go
  pkg/frontendconfig/frontendconfig.go
  pkg/frontendconfig/frontendconfig_test.go
  pkg/loadbalancers/features/doc.go
  pkg/loadbalancers/l7.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/batch_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/test/frontendconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#761 Add option to override gce endpoint in test
  cmd/e2e-test/main_test.go
  cmd/fuzzer/app/validate.go
  pkg/e2e/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/M
