Repository kubernetes/ingress-gce, pull requests merged in 2019-01, with the labels that each got.

#576 do not use condition predicate while getting zone for node
  pkg/controller/translator/translator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#594 add unit test for GetZoneForNode helper func
  pkg/controller/translator/translator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#587 [1.4 Cherry pick] Revert "Remove unused named ports from instance group's"
  pkg/instances/instances.go
  pkg/instances/instances_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#600 Delete documentation that is now covered by GCP docs
  README.md
  docs/README.md
  docs/admin.md
  docs/annotations.md
  docs/troubleshooting/troubleshooting.md
  examples/PREREQUISITES.md
  examples/backside-https/app.yaml
  examples/deployment/README.md
  examples/deployment/gce-ingress-controller.yaml
  examples/deployment/gce-tls-ingress.yaml
  examples/health-checks/README.md
  examples/health-checks/health_check_app.yaml
  examples/http-svc.yaml
  examples/https/Makefile
  examples/https/README.md
  examples/https/tls-app.yaml
  examples/multi-path/gce-multi-path-ingress.yaml
  examples/multi-path/svc.yaml
  examples/static-ip/README.md
  examples/static-ip/gce-http-ingress.yaml
  examples/static-ip/gce-static-ip-ingress.yaml
  examples/tls-termination/README.md
  examples/tls-termination/gce-tls-ingress.yaml
  examples/websocket/Dockerfile
  examples/websocket/README.md
  examples/websocket/deployment.yaml
  examples/websocket/server.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XXL

#601 Add link to OSS Ingress docs in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#604 Add changelog for v1.4.1 + Add config file for github-changelog-generator
  .github_changelog_generator
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#590 Replace all uses of Snapshotter with CloudLister
  pkg/backends/backends.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/interfaces.go
  pkg/backends/neg_linker_test.go
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/types.go
  pkg/instances/fakes.go
  pkg/instances/instances.go
  pkg/instances/instances_test.go
  pkg/instances/interfaces.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/storage/pools.go
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#609 do not use condition predicate while getting zone for node
  pkg/controller/translator/translator.go
Labels: approved, cncf-cla: yes, lgtm

#607 standardize loadbalancer naming for GC
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/namer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#611 [BackendConfig] CDN default cache key policy should be true instead of false.
  pkg/backends/features/cdn.go
  pkg/backends/features/cdn_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#615 Add changelog for 1.4.2 release
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#618 make backoff retry handler unit test faster
  pkg/neg/syncers/retry_handler.go
  pkg/neg/syncers/retry_handler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#613 Add Finalizers for Ingress
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/types.go
  pkg/flags/flags.go
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
