Repository kubernetes/ingress-gce, pull requests merged in 2019-09, with the labels that each got.

#841 try to spread the pods across zone to avoid test timeout
  cmd/e2e-test/neg_test.go
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#842 fix a typo
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#843 Update e2e framework for ILB - Part 1
  cmd/e2e-test/ilb_test.go
  pkg/e2e/helpers.go
  pkg/fuzz/features/features.go
  pkg/fuzz/features/ilb.go
  pkg/fuzz/features/neg.go
  pkg/fuzz/helpers.go
  pkg/fuzz/validator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#838 Bugfix: don't GC instance groups while multi-cluster ingresses exist
  pkg/common/operator/ingress.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/types.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#845 Remove word 'Basic' from ILB e2e test
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#847 Use protobufs for communication with apiserver
  cmd/glbc/app/clients.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#840 Cherrypick #834 into release 1.6
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#851 De-dupe additional source ranges for firewall
  pkg/firewalls/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#853 Cherry pick #851
  pkg/firewalls/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#848 Add more e2e tests for L7-ILB
  cmd/e2e-test/basic_https_test.go
  cmd/e2e-test/ilb_test.go
  pkg/e2e/cert.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#862 Some documentation fixes to reflect current state of world
  LIMITATIONS.md
  README.md
  docs/faq/gce.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#859 Refactor namer into a separate package
  cmd/glbc/app/namer.go
  pkg/backends/backends.go
  pkg/backends/ig_linker.go
  pkg/backends/neg_linker.go
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator_test.go
  pkg/firewalls/controller_test.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
  pkg/fuzz/default_validator_env.go
  pkg/fuzz/validator.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/instances/fakes.go
  pkg/instances/instances.go
  pkg/instances/instances_test.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/syncers/batch_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/utils/namer/namer.go
  pkg/utils/namer/namer_test.go
  pkg/utils/namer/utils.go
  pkg/utils/namer/utils_test.go
  pkg/utils/serviceport.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#865 Bugfix: Pass updated ingress for validation
  cmd/e2e-test/finalizer_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#864 split the error message in backend syncer health processing
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, size/XS

#869 Update list subnets call to Beta for L7-ILB
  pkg/loadbalancers/features/l7ilb.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#846 e2e test framework add support for ilb subnet
  cmd/e2e-test/main_test.go
  cmd/e2e-test/run.sh
  pkg/e2e/fixtures.go
  pkg/e2e/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#849 Cherrypick to 1.6 branch: Use protobufs for communication with apiserver
  cmd/glbc/app/clients.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#850 Cherrypick to 1.7 branch: Use protobufs for communication with apiserver
  cmd/glbc/app/clients.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#870 Add CreateILBSubnet() call to all ilb e2e tests
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#871 Update ILB e2e test resource names
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#603 Add scaffolding for supporting additional whitebox testing
  cmd/e2e-test/basic_https_test.go
  cmd/e2e-test/basic_test.go
  cmd/e2e-test/neg_test.go
  cmd/e2e-test/upgrade_test.go
  cmd/fuzzer/app/validate.go
  go.mod
  go.sum
  pkg/e2e/helpers.go
  pkg/fuzz/validator.go
  pkg/fuzz/validator_test.go
  pkg/fuzz/whitebox.go
  pkg/fuzz/whitebox/num_backend_services.go
  pkg/fuzz/whitebox/num_forwarding_rules.go
  pkg/fuzz/whitebox/whitebox_tests.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#874 Update IngressPollTimeout to 45 minutes
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#867 Separate out health check errors for Backends
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#873 Update CreateILBSubnet() to catch 400s as well
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#878 Fix backend services whitebox test to take into account the default backend
  pkg/fuzz/whitebox/num_backend_services.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#876 Disable Http on ILB Https e2e tests
  cmd/e2e-test/ilb_test.go
  pkg/fuzz/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
