Repository kubernetes/ingress-gce, pull requests merged in 2019-10, with the labels that each got.

#880 Fix basic ilb test service name
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#881 BugFix: Update ingress key function used for GC
  pkg/controller/controller.go
  pkg/neg/controller.go
  pkg/utils/namer/utils.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#884 Fix Ingress names for ILB e2e update test
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#883 Refactor ingress key function and finalizer into separate package
  cmd/e2e-test/finalizer_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/e2e/helpers.go
  pkg/firewalls/controller_test.go
  pkg/fuzz/features/neg.go
  pkg/neg/controller.go
  pkg/utils/common/common.go
  pkg/utils/common/finalizer.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#885 Fix CreateILBSubnet() logic in e2e tests
  cmd/e2e-test/ilb_test.go
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#804 Add support for composite types for zonal resources
  pkg/composite/gen.go
  pkg/composite/gen/main.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#886 remove "addonmanager.kubernetes.io/mode: Reconcile" annotation from
  docs/deploy/gke/csm/default-http-backend.yaml
  docs/deploy/resources/default-http-backend.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#887 Add v1.5.2, v1.6.0 and v1.7.0 to CHANGELOG.md
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#888 Update version mapping in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#889 remove add on manager labels
  docs/deploy/gke/csm/default-http-backend.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#861 Cleanup backend namer workflow
  pkg/backends/backends.go
  pkg/backends/ig_linker.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/firewalls/controller.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/instances/instances.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#893 Add -network flag to e2e test framework for ILB subnet creation
  cmd/e2e-test/main_test.go
  pkg/e2e/fixtures.go
  pkg/e2e/framework.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#895 Fix ILB subnet discovery to check for VPC as well
  pkg/loadbalancers/features/l7ilb.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#896 Shorten ILB e2e ingress names to less than 20 characters to avoid leaks
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#897 Cherry pick #895 into 1 7
  pkg/loadbalancers/features/l7ilb.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#890 Cherry Pick #869 [Update list subnets call to Beta for L7-ILB] to release-1.7
  pkg/loadbalancers/features/l7ilb.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#899 Shorten all ILB e2e ingress test names again since we actually only have 10 characters
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#902 Cherry pick #881 into 1.7
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#900 enqueue default backend for NEG processing
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#903 Cherry pick #900 into release-1.7
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#901 Cleanup e2e tests to use whitebox testing
  cmd/e2e-test/basic_https_test.go
  cmd/e2e-test/basic_test.go
  cmd/e2e-test/finalizer_test.go
  cmd/e2e-test/neg_test.go
  cmd/e2e-test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#860 Migrating existing front-end namer logic to Legacy
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/neg/controller.go
  pkg/utils/common/common.go
  pkg/utils/namer/frontendnamer.go
  pkg/utils/namer/frontendnamer_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#904 Add go-cmp to dependencies
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#906 Fix ILB forwarding rule bug
  pkg/loadbalancers/features/l7ilb.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#907 Cherry Pick #906 (Fix ILB forwarding rule bug) to release-1.7
  pkg/loadbalancers/features/l7ilb.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#856 refactor neg controller: processService, add unittest
  pkg/annotations/destination_rule.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#911 Plumb region to neg validator for e2e testing
  pkg/e2e/helpers.go
  pkg/fuzz/features/neg.go
  pkg/fuzz/validator.go
  pkg/fuzz/validator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#877 Check for invalid L7-ILB HTTPS configuration
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#915 Bump TestAffinity transition timeout from 5 to 10 minutes
  cmd/e2e-test/affinity_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#912 Handle cache.DeletedFinalStateUnknown
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#916 remove batch syncer and move the unit test utils
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/batch.go
  pkg/neg/syncers/batch_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#918 Cherry pick #912 [Handle cache.DeletedFinalStateUnknown] to release-1.7
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#920 Add a flag for Non-GCP mode NEG controller.
  pkg/flags/flags.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#922 move neg type into syncerKey
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#923 Support more methods in composite NEGs.
  pkg/composite/gen.go
  pkg/composite/gen/main.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#924 Update forwarding rule logic for l7-ilb
  pkg/loadbalancers/features/l7ilb.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
