Repository kubernetes/ingress-gce, pull requests merged in 2019-02, with the labels that each got.

#626 Cherry-picking #547 onto 1.4 branch
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#627 Cherry-pick #613 onto 1.4, part 1
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/types.go
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, ok-to-test, size/M

#628 Cherry-pick #613 onto 1.4 branch
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/flags/flags.go
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#630 Update GKE version mapping in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#633 Cherrypick #582 into release-1.4 branch
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#624 Cherrypick #623 on 1.4 branch
  cmd/glbc/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 Revert "Cherry-pick #613 onto 1.4 branch"
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/flags/flags.go
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#636 Revert "Cherry-pick #613 onto 1.4, part 1"
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/types.go
  pkg/utils/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#597 Switch to use the beta+ NEG API
  pkg/neg/syncers/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#619 Add more unit tests for transaction syncer
  pkg/neg/syncers/syncer.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/mock.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#643 Update CHANGELOG and version mapping for v1.4.3
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#644 Move lone function in kubeapi.go into existing utils.go
  pkg/utils/kubeapi.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#641 Support secret-based and pre-shared certs at the same time
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#648 Shorten the name of the namespace for test sandboxes
  pkg/e2e/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#650 Modify NameBelongToCluter to tolerate truncated cluster name suffix
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#652 Cherrypick #650 into release 1.5 branch
  pkg/utils/namer.go
  pkg/utils/namer_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#653 Revert "Shorten the name of the namespace for test sandboxes"
  pkg/e2e/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
