Repository kubernetes/ingress-gce, pull requests merged in 2020-05, with the labels that each got.

#1090 Replace GCE_PRIMARY_VM_IP to GCE_VM_IP NEG.
  pkg/backends/features/features.go
  pkg/backends/syncer_test.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/types.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/namer.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1091 Update L7-ILB API to GA
  pkg/healthchecks/healthchecks_test.go
  pkg/loadbalancers/features/features.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1089 Cherry-pick #1082 to release-1.9 [Update FrontendConfig v1beta1 API so that Spec and Status fields are omitempty]
  pkg/apis/frontendconfig/v1beta1/types.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1097 Cherrypick #1076[Return GCE LB deletion error] into release-1.7
  pkg/loadbalancers/l7s.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1098 Cherrypick #1076[Return GCE LB deletion error] into release-1.8
  pkg/loadbalancers/l7s.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1099 Cherrypick #1076[Return GCE LB deletion error] into release-1.9
  pkg/loadbalancers/l7s.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1096 Enable pruning of unknown fields for CRDs
  pkg/backendconfig/backendconfig.go
  pkg/crd/crd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1103 Add test for pruning unknown fields of CRDs
  pkg/crd/crd_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1080 Fail ingress creation if specified staticIP name does not exist
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1102 Wait for backendconfig CRD to be established
  pkg/e2e/framework.go
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1104 Change project permissions check from 'foo' to 'k8s-ingress-svc-acct-…
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1083 e2e tests for SslPolicy
  cmd/e2e-test/sslpolicy_test.go
  pkg/e2e/framework.go
  pkg/fuzz/helpers.go
  pkg/loadbalancers/target_proxies.go
Labels: approved, cncf-cla: yes, ok-to-test, size/L

#1107 Wait for caches to sync before running node sync
  pkg/controller/node.go
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, size/M

#1092 Add support for Port to BackendConfig HealthCheckConfig
  cmd/e2e-test/healthcheck_test.go
  pkg/apis/backendconfig/v1/types.go
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1109 Cherrypick PR 1090 to release-1.9
  pkg/backends/features/features.go
  pkg/backends/syncer_test.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/types.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/namer.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1110 Script to run local e2e test
  hack/run-local-glbc.sh
  hack/setup-local.sh
Labels: approved, cncf-cla: yes, size/L

#1111 Cherrypick #1096[Enable pruning of unknown fields for CRDs] into release-1.9
  pkg/backendconfig/backendconfig.go
  pkg/crd/crd.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1108 Cherry-Pick #1092 [Add support for Port to BackendConfig HealthCheckConfig] to release-1.9
  pkg/apis/backendconfig/v1/types.go
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1113 Cherry Pick #1104 [Change project permissions check from 'foo' to 'k8s-ingress-svc-acct-...] to release-1.9…
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1116 Update generated code for BackendConfig
  cmd/e2e-test/affinity_beta_test.go
  go.sum
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/backendconfig/client/clientset/versioned/clientset.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/fake/fake_backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/fake/fake_backendconfig.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1/backendconfig.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1beta1/backendconfig.go
  pkg/e2e/adapter/beconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1114 Cherry Pick #1107 [Wait for caches to sync before running node sync] to release-1.9
  pkg/controller/node.go
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1115 Update generated code for BackendConfig in release-1.9
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1094 Add e2e tests for backendconfig access logging
  cmd/e2e-test/logging_test.go
  pkg/fuzz/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1119 Force send Enable field for LogConfig
  pkg/backends/features/logging.go
  pkg/composite/gen.go
  pkg/composite/gen/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1120 Cherrpick #1119 [Force send Enable field for LogConfig] into release-1.9
  pkg/backends/features/logging.go
  pkg/composite/gen.go
  pkg/composite/gen/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1101 Initial refactors to bootstrap self-contained translator
  hack/run-local-glbc.sh
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/url_maps.go
  pkg/loadbalancers/url_maps_test.go
  pkg/tls/tls.go
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: approved, cncf-cla: yes, size/XL

#1105 do not sync IG when not necessary
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1121 Cherrypick #1105 into Release-1.9
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1112 Cherrypick PR 1080 into release-1.9
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
