Repository kubernetes/ingress-gce, pull requests merged in 2020-11, with the labels that each got.

#1292 Update SSLPolicy e2e test to use a unique policy name
  cmd/e2e-test/sslpolicy_test.go
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1312 This PR fixes the /metrics from being exposed to the Internet by
  Dockerfile.404-server-with-metrics
  cmd/404-server-with-metrics/prometheus.yml
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: cncf-cla: yes, ok-to-test, size/M

#1316 Prevent Empty Neg Refs on CRs
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/types/fakes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1317 Cherry Pick #1316 [Prevent Empty Neg Refs on CRs] to release 1.10
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/types/fakes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1320 Cherry-pick #1312 [This PR fixes the /metrics from being exposed to the Internet...] into release-1-10
  Dockerfile.404-server-with-metrics
  cmd/404-server-with-metrics/prometheus.yml
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1321 Log the Forwarding rule diff in L4 ILB.
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1311 Add Service Attachment CRD for PSC Alpha
  hack/update-codegen.sh
  pkg/apis/serviceattachment/register.go
  pkg/apis/serviceattachment/v1alpha1/doc.go
  pkg/apis/serviceattachment/v1alpha1/register.go
  pkg/apis/serviceattachment/v1alpha1/types.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
  pkg/serviceattachment/client/clientset/versioned/clientset.go
  pkg/serviceattachment/client/clientset/versioned/doc.go
  pkg/serviceattachment/client/clientset/versioned/fake/clientset_generated.go
  pkg/serviceattachment/client/clientset/versioned/fake/doc.go
  pkg/serviceattachment/client/clientset/versioned/fake/register.go
  pkg/serviceattachment/client/clientset/versioned/scheme/doc.go
  pkg/serviceattachment/client/clientset/versioned/scheme/register.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/doc.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/doc.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/fake_serviceattachment.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/fake_serviceattachment_client.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/generated_expansion.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/serviceattachment.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/serviceattachment_client.go
  pkg/serviceattachment/client/informers/externalversions/factory.go
  pkg/serviceattachment/client/informers/externalversions/generic.go
  pkg/serviceattachment/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/interface.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/v1alpha1/interface.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/v1alpha1/serviceattachment.go
  pkg/serviceattachment/client/listers/serviceattachment/v1alpha1/expansion_generated.go
  pkg/serviceattachment/client/listers/serviceattachment/v1alpha1/serviceattachment.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1322 Add logs to include what changed in a forwarding rule.
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1323 Do not return the path in response to a bad request path to avoid cro…
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1327 Cherry pick to release-1.10 Do not return the path in response to a bad request path to avoid cro…
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1325 remove EnableNonGCPMode flag from NEG controller
  cmd/glbc/main.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: approved, cncf-cla: yes, size/L

#1326 remove EnableNegCrd flag
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: approved, cncf-cla: yes, size/L

#1330 Increase Neg GC Poll timeout
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1318 GCPIngressParams CRD
  hack/update-codegen.sh
  pkg/apis/ingparams/register.go
  pkg/apis/ingparams/v1beta1/doc.go
  pkg/apis/ingparams/v1beta1/register.go
  pkg/apis/ingparams/v1beta1/types.go
  pkg/apis/ingparams/v1beta1/zz_generated.deepcopy.go
  pkg/apis/ingparams/v1beta1/zz_generated.openapi.go
  pkg/ingparams/client/clientset/versioned/clientset.go
  pkg/ingparams/client/clientset/versioned/doc.go
  pkg/ingparams/client/clientset/versioned/fake/clientset_generated.go
  pkg/ingparams/client/clientset/versioned/fake/doc.go
  pkg/ingparams/client/clientset/versioned/fake/register.go
  pkg/ingparams/client/clientset/versioned/scheme/doc.go
  pkg/ingparams/client/clientset/versioned/scheme/register.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/doc.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/doc.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/fake_gcpingressparams.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/fake_ingparams_client.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/gcpingressparams.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/generated_expansion.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/ingparams_client.go
  pkg/ingparams/client/informers/externalversions/factory.go
  pkg/ingparams/client/informers/externalversions/generic.go
  pkg/ingparams/client/informers/externalversions/ingparams/interface.go
  pkg/ingparams/client/informers/externalversions/ingparams/v1beta1/gcpingressparams.go
  pkg/ingparams/client/informers/externalversions/ingparams/v1beta1/interface.go
  pkg/ingparams/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/ingparams/client/listers/ingparams/v1beta1/expansion_generated.go
  pkg/ingparams/client/listers/ingparams/v1beta1/gcpingressparams.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1328 Ensure ServiceAttachment CRD when PSC is enabled
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/serviceattachment/serviceattachment.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
