Repository kubernetes/ingress-gce, pull requests merged in 2020-09, with the labels that each got.

#1244 cherrypick PR 1236(resource annotations for ILB) into release-1.10
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/utils/patch.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1227 Update ensureRedirectUrlMap() logic
  pkg/loadbalancers/url_maps.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1245 Cherry-pick #1227 [Update ensureRedirectUrlMap() logic] into release-1.10
  pkg/loadbalancers/url_maps.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1246 Require id in NegObjectReference
  pkg/apis/svcneg/v1beta1/types.go
  pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1247 Cherry Pick #1246 [Require id cherry pick]
  pkg/apis/svcneg/v1beta1/types.go
  pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1118 Update CRD client(apiextensions) to v1
  pkg/backendconfig/backendconfig.go
  pkg/crd/crd.go
  pkg/crd/crd_test.go
  pkg/crd/meta.go
  pkg/crd/validation.go
  pkg/frontendconfig/frontendconfig.go
  pkg/svcneg/svcneg.go
Labels: cncf-cla: yes, ok-to-test, size/L

#1251 Remove extra L7-ILB Testcase
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1248 Fix a couple bugs in the redirects e2e test
  cmd/e2e-test/basic_https_test.go
  cmd/e2e-test/basic_test.go
  cmd/e2e-test/finalizer_test.go
  cmd/e2e-test/neg_test.go
  cmd/e2e-test/redirects_test.go
  cmd/e2e-test/sslpolicy_test.go
  cmd/e2e-test/upgrade/basic_http.go
  cmd/e2e-test/upgrade/finalizer.go
  cmd/e2e-test/upgrade/v2frontendnamer.go
  cmd/e2e-test/v2frontendnamer_test.go
  pkg/e2e/helpers.go
  pkg/fuzz/features/https_redirects.go
  pkg/fuzz/validator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1256 Add support for external workload
  Dockerfile.workload-controller
  Dockerfile.workload-daemon
  Makefile
  cmd/workload-controller/app/client.go
  cmd/workload-controller/main.go
  cmd/workload-daemon/main.go
  docs/experimental/workload/README.md
  docs/experimental/workload/controller-deploy.yaml
  docs/experimental/workload/rbac.yaml
  hack/run-local-workload-controller.sh
  hack/update-experimental-codegen.sh
  pkg/experimental/apis/workload/register.go
  pkg/experimental/apis/workload/v1alpha1/doc.go
  pkg/experimental/apis/workload/v1alpha1/register.go
  pkg/experimental/apis/workload/v1alpha1/types.go
  pkg/experimental/apis/workload/v1alpha1/zz_generated.deepcopy.go
  pkg/experimental/apis/workload/v1alpha1/zz_generated.openapi.go
  pkg/experimental/metadata/metadata.go
  pkg/experimental/workload/client/clientset/versioned/clientset.go
  pkg/experimental/workload/client/clientset/versioned/doc.go
  pkg/experimental/workload/client/clientset/versioned/fake/clientset_generated.go
  pkg/experimental/workload/client/clientset/versioned/fake/doc.go
  pkg/experimental/workload/client/clientset/versioned/fake/register.go
  pkg/experimental/workload/client/clientset/versioned/scheme/doc.go
  pkg/experimental/workload/client/clientset/versioned/scheme/register.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/doc.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/fake/doc.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/fake/fake_workload.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/fake/fake_workload_client.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/generated_expansion.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/workload.go
  pkg/experimental/workload/client/clientset/versioned/typed/workload/v1alpha1/workload_client.go
  pkg/experimental/workload/client/informers/externalversions/factory.go
  pkg/experimental/workload/client/informers/externalversions/generic.go
  pkg/experimental/workload/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/experimental/workload/client/informers/externalversions/workload/interface.go
  pkg/experimental/workload/client/informers/externalversions/workload/v1alpha1/interface.go
  pkg/experimental/workload/client/informers/externalversions/workload/v1alpha1/workload.go
  pkg/experimental/workload/client/listers/workload/v1alpha1/expansion_generated.go
  pkg/experimental/workload/client/listers/workload/v1alpha1/workload.go
  pkg/experimental/workload/controller.go
  pkg/experimental/workload/controller_test.go
  pkg/experimental/workload/daemon/daemon.go
  pkg/experimental/workload/daemon/provider/gce/vm.go
  pkg/experimental/workload/daemon/utils/interface.go
  pkg/experimental/workload/daemon/utils/kube-config.go
  pkg/experimental/workload/daemon/utils/template.go
  pkg/experimental/workload/workload.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1250 Refactor transition e2e tests to use t.Run()
  cmd/e2e-test/affinity_beta_test.go
  cmd/e2e-test/ilb_test.go
  cmd/e2e-test/neg_test.go
  cmd/e2e-test/redirects_test.go
  cmd/e2e-test/security_policy_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1254 Make sure L4 Forwarding rule is atmost 63 characters
  pkg/context/context.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/test/utils.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
  pkg/utils/namer/namer.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1258 Cherrypick of L4 V2 Namer PR - 1254
  pkg/context/context.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/test/utils.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
  pkg/utils/namer/namer.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1261 Fix Pre-shared Cert Region for ILB HTTPS Tests
  cmd/e2e-test/ilb_test.go
  pkg/e2e/cert.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1262 Add NegCRD Upgrade Test
  cmd/e2e-test/upgrade/neg.go
  cmd/e2e-test/upgrade_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1257 Update version mapping and Changelog
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1264 Ensure neg crs for all desired ports
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1265 Cherry Pick #1264 [Ensure neg cr cherry pick]
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1263 Fix SSL Certs Leak in ILB Tests
  pkg/e2e/cert.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1266 ensure ingress controller always generate consistent uid and provider uid
  cmd/glbc/app/namer.go
  pkg/storage/configmaps.go
  pkg/storage/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1259 Fix GC for switching between LB Scopes on Namer V2
  pkg/annotations/ingress.go
  pkg/controller/controller.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/url_maps.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1270 Update docs to run binaries locally
  cmd/e2e-test/readme.md
  docs/deploy/local/README.md
  hack/run-local-glbc.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1267 skip opening firewall for node port ranges when unnecessary
  pkg/firewalls/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
  pkg/firewalls/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1273 Cherry-pick #1259 [Fix GC for switching between LB Scopes on Namer V2] into release-1-9
  pkg/annotations/ingress.go
  pkg/controller/controller.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1272 Cherry-pick #1259 [Fix GC for switching between LB Scopes on Namer V2] into release-1-10
  pkg/annotations/ingress.go
  pkg/controller/controller.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/url_maps.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1269 Fix NEG handling for default backend service when it contains the NEG annotation
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1275 Cherry Pick #1269 [fix NEG handling for default backend service when it contains the NEG annotation] to 1.10
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1277 Cherry Pick #1269 [fix NEG handling for default backend service when it contains the NEG annotation] to 1.9
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1276 Cherry Pick #1266 [ensure ingress controller always generate consistent uid and provider uid]
  cmd/glbc/app/namer.go
  pkg/storage/configmaps.go
  pkg/storage/configmaps_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1274 Cherry Pick #1267 [skip opening firewall for node port ranges when unnecessary]
  pkg/firewalls/controller.go
  pkg/firewalls/firewalls.go
  pkg/firewalls/firewalls_test.go
  pkg/firewalls/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1281 Cherry Pick #1280 [Change neg metric name]
  pkg/neg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1280 Change neg metric name
  pkg/neg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
