Repository kubernetes/ingress-gce, pull requests merged in 2020-12, with the labels that each got.

#1315 Support for Path Type
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1333 Switch to using beta neg API for VM_IP_NEGs.
  pkg/backends/features/features.go
  pkg/neg/types/mock.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1331 Remove pkg/context dependency from NEG controller
  cmd/glbc/main.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/testing.go
Labels: approved, cncf-cla: yes, size/XL

#1340 Switch to using beta API for VM_IP_NEGs.
  pkg/backends/features/features.go
  pkg/neg/types/mock.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1332 Ensure GCPIngressParams CRD
  cmd/glbc/app/init.go
  cmd/glbc/main.go
  cmd/workload-controller/main.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator_test.go
  pkg/crd/crd.go
  pkg/crd/crd_test.go
  pkg/firewalls/controller_test.go
  pkg/ingparams/ingparams.go
  pkg/l4/l4controller_test.go
  pkg/neg/controller_test.go
  pkg/neg/types/testing.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1338 Add a new metric for L4 ILB Sync latency
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/metrics/metrics.go
  pkg/test/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1339 Refactor SSLPolicy e2e tests
  cmd/e2e-test/sslpolicy_test.go
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1341 Cherrypick ILB latency metric addition into 1.10
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/metrics/metrics.go
  pkg/test/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1342 Update svcNeg resources with original neg CR
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1343 Cherrypick #1342 to release 1.10 [Update svcNeg resources with original neg CR]
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1344 Support specifying more than 5 ports in L4 ILB service
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1345 Support specifying more than 5 ports in L4 ILB service
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1347 Autogenerated output of `go mod vendor`
  go.mod
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1346 Update vendor and go.mod
  go.mod
  vendor/go.opencensus.io/plugin/ocgrpc/client.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/client_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/doc.go
  vendor/go.opencensus.io/plugin/ocgrpc/server.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_metrics.go
  vendor/go.opencensus.io/plugin/ocgrpc/server_stats_handler.go
  vendor/go.opencensus.io/plugin/ocgrpc/stats_common.go
  vendor/go.opencensus.io/plugin/ocgrpc/trace_common.go
  vendor/google.golang.org/api/transport/dial.go
  vendor/google.golang.org/api/transport/doc.go
  vendor/google.golang.org/api/transport/go19.go
  vendor/google.golang.org/api/transport/grpc/dial.go
  vendor/google.golang.org/api/transport/grpc/dial_appengine.go
  vendor/google.golang.org/api/transport/grpc/dial_socketopt.go
  vendor/google.golang.org/api/transport/grpc/pool.go
  vendor/google.golang.org/api/transport/not_go19.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.pb.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.proto
  vendor/google.golang.org/appengine/socket/doc.go
  vendor/google.golang.org/appengine/socket/socket_classic.go
  vendor/google.golang.org/appengine/socket/socket_vm.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer.pb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_config.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_picker.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_remote_balancer.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpclb_util.go
  vendor/google.golang.org/grpc/balancer/grpclb/regenerate.sh
  vendor/google.golang.org/grpc/credentials/alts/alts.go
  vendor/google.golang.org/grpc/credentials/alts/internal/authinfo/authinfo.go
  vendor/google.golang.org/grpc/credentials/alts/internal/common.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/aeadrekey.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/aes128gcm.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/aes128gcmrekey.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/common.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/counter.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/record.go
  vendor/google.golang.org/grpc/credentials/alts/internal/conn/utils.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/handshaker.go
  vendor/google.golang.org/grpc/credentials/alts/internal/handshaker/service/service.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/altscontext.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/transport_security_common.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/regenerate.sh
  vendor/google.golang.org/grpc/credentials/alts/utils.go
  vendor/google.golang.org/grpc/credentials/google/google.go
  vendor/google.golang.org/grpc/credentials/oauth/oauth.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL
