Repository kubernetes/ingress-gce, pull requests merged in 2020-07, with the labels that each got.

#1166 Neg crd feature gate
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
  pkg/svcneg/svcneg.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1168 Initial Refactor of TargetProxy to Translator Package
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: cncf-cla: yes, ok-to-test, size/XL

#1175 Update GKE version mapping
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1173 Update k8s-cloud-provider to 1.13.0
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/filter/filter.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/op.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/component-base/featuregate/feature_gate.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1179 Cleanup Internal IP reservation after L4 ILB creation
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1137 Add events for major lifecycle events
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/events/events.go
  pkg/events/events_test.go
  pkg/instances/instances.go
  pkg/instances/instances_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/test/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1180 Fix VM_IP_NEG creation and updates
  pkg/backends/backends.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/neg/controller.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1184 Cherrypick: Wait for caches to sync before running node sync
  pkg/controller/node.go
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1185 Cherrypick: Wait for caches to sync before running node sync
  pkg/controller/node.go
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1172 Create corresponding Neg CRs when NEG CRD is enabled
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator_test.go
  pkg/firewalls/controller_test.go
  pkg/l4/l4controller_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/svcneg/svcneg.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1188 Revert to individual secret get
  docs/deploy/resources/rbac.yaml
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1167 Move APIs to work with health checks into translator package to prepare for future refactoring
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecks/interfaces.go
  pkg/translator/healthchecks.go
  pkg/utils/healthchecks.go
Labels: approved, cncf-cla: yes, size/XL

#1181 Cleanup L4 ILB IP Reservation in all cases.
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1192 Handle error when calculating endpoints for NEG.
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1193 Handle error when calculating endpoints for NEG.
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1144 Ensure ingress cleanup when finalizer exists
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1194 Cherrypick #1144 [Ensure ingress cleanup when finalizer exists] into release-1.9
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1174 Implement support for Internal/Regional Static IP for L7-ILB
  pkg/annotations/ingress.go
  pkg/annotations/ingress_test.go
  pkg/composite/gen.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
  pkg/controller/controller.go
  pkg/fuzz/features/static_ip.go
  pkg/fuzz/helpers.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/addresses_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1187 syncer writes neg desc on initialization
  pkg/apis/svcneg/v1beta1/types.go
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
  pkg/utils/namer/namer.go
  pkg/utils/negdescription.go
  pkg/utils/negdescription_test.go
  pkg/utils/patch.go
  pkg/utils/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1196 Add repo SECURITY.md
  SECURITY.md
Labels: cncf-cla: yes, size/S

#1200 Cherry pick #1173 [Update k8s-cloud-provider to 1.13.0] into release 1.9
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/filter/filter.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/op.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/OWNERS
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#1201 Cherry pick #1174 [Implement support for Internal/Regional Static IP for L7-ILB] into release-1.9
  pkg/annotations/ingress.go
  pkg/annotations/ingress_test.go
  pkg/composite/gen.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
  pkg/controller/controller.go
  pkg/fuzz/features/static_ip.go
  pkg/fuzz/helpers.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/addresses_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1199 Ignore deletion timestamp when ensuring NEG CR
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1191 Allow modifying trafficPolicy for L4 ILB services
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L
