Repository kubernetes/ingress-gce, pull requests merged in 2020-06, with the labels that each got.

#1123 Use patch for updating ingress/service finalizers
  pkg/utils/common/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1124 Add back local run script which was deleted
  hack/run-local-glbc.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1125 Replace Ingress resource Update calls with Patch
  pkg/controller/controller.go
  pkg/utils/common/common.go
  pkg/utils/common/finalizer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1128 Add rbac permissions for networking.gke.io/frontendconfigs
  docs/deploy/resources/rbac.yaml
  hack/update-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1129 Cherry-pick #1128 to release-1.9 [Add rbac permissions for networking.gke.io/frontendconfigs]
  docs/deploy/resources/rbac.yaml
  hack/update-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1133 Update changelog for multiple release versions
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1130 Update GKE version mappings
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1135 run-local-glbc.sh needs to capture stderr in the log
  hack/run-local-glbc.sh
Labels: approved, cncf-cla: yes, size/XS

#1136 Remove cluster-service annotation to avoid conflicting with GKE addon…
  docs/deploy/resources/default-http-backend.yaml
Labels: approved, cncf-cla: yes, size/XS

#1134 Remove unnecessary `update` permissions
  docs/deploy/resources/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1138 Set access logging sampling rate to be 1
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1140 Cherrypick #1138 [Set access logging sampling rate to be 1] into release-1.7
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1142 Cherrypick #1138 [Set access logging sampling rate to be 1] into release-1.9
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1139 Cherrypick #1138 [Set access logging sampling rate to be 1] into release-1.6
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1141 Cherrypick #1138 [Set access logging sampling rate to be 1] into release-1.8
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1145 Wait for NEGs deletion based on deletion option
  pkg/fuzz/gcp.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1156 Commented out broken link
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1157 Fix broken link in faq
  docs/faq/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1155 add logging in NEG syncer
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1158 Cherrypicking #1155 into release 1.9
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1159 Add open API validation for Security Policy
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1161 Cherrypick #1159 [Fix Security Policy Config for Open API gen] into release-1.9
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1126 Add translation for ForwardingRule
  pkg/loadbalancers/forwarding_rules.go
  pkg/tls/tls.go
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: approved, cncf-cla: yes, size/L

#1162 Avoid unnecessary backend service update in NEG linker
  pkg/backends/features/features.go
  pkg/backends/neg_linker.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1154 Add NEG CRD definition
  hack/update-codegen.sh
  pkg/apis/svcneg/register.go
  pkg/apis/svcneg/v1beta1/doc.go
  pkg/apis/svcneg/v1beta1/register.go
  pkg/apis/svcneg/v1beta1/types.go
  pkg/apis/svcneg/v1beta1/zz_generated.deepcopy.go
  pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
  pkg/svcneg/client/clientset/versioned/clientset.go
  pkg/svcneg/client/clientset/versioned/doc.go
  pkg/svcneg/client/clientset/versioned/fake/clientset_generated.go
  pkg/svcneg/client/clientset/versioned/fake/doc.go
  pkg/svcneg/client/clientset/versioned/fake/register.go
  pkg/svcneg/client/clientset/versioned/scheme/doc.go
  pkg/svcneg/client/clientset/versioned/scheme/register.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/doc.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/fake/doc.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/fake/fake_servicenetworkendpointgroup.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/fake/fake_svcneg_client.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/generated_expansion.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/servicenetworkendpointgroup.go
  pkg/svcneg/client/clientset/versioned/typed/svcneg/v1beta1/svcneg_client.go
  pkg/svcneg/client/informers/externalversions/factory.go
  pkg/svcneg/client/informers/externalversions/generic.go
  pkg/svcneg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/svcneg/client/informers/externalversions/svcneg/interface.go
  pkg/svcneg/client/informers/externalversions/svcneg/v1beta1/interface.go
  pkg/svcneg/client/informers/externalversions/svcneg/v1beta1/servicenetworkendpointgroup.go
  pkg/svcneg/client/listers/svcneg/v1beta1/expansion_generated.go
  pkg/svcneg/client/listers/svcneg/v1beta1/servicenetworkendpointgroup.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL
