Repository kubernetes/ingress-gce, pull requests merged in 2020-02, with the labels that each got.

#929 fix misspell failures
  pkg/annotations/ingress.go
  pkg/composite/gen.go
  pkg/e2e/framework.go
  pkg/e2e/helpers.go
  pkg/fuzz/features/app_protocol.go
  pkg/neg/controller.go
  pkg/neg/syncers/transaction_test.go
  pkg/utils/namer/namer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#930 fix golint failures
  pkg/backends/syncer.go
  pkg/healthchecks/healthchecks.go
  pkg/instances/interfaces.go
  pkg/neg/types/network_endpoint.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1004 Handle zones with non-uniform node count in L4 ILB Subsetting
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/subsets.go
  pkg/neg/syncers/subsets_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1012 Make metrics label Snake case compliant
  pkg/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1006 added test case TestBasicWindows
  cmd/e2e-test/basic_test.go
  pkg/e2e/fixtures.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1011 Remove enable-istio flag for e2e test.
  cmd/e2e-test/asm_test.go
  cmd/e2e-test/main_test.go
  pkg/e2e/framework.go
  pkg/e2e/sandbox.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1017 Update k8s-cloud-provider to 1.12.0
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/mock/mock.go
  vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1021 Add SetSslPolicyForTargetHttpsProxy() to composite
  pkg/composite/composite.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1015 Cherrypick #976, #984, #990 and #1012 [Ingress Usage metrics] into release 1.8
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/types.go
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1020 Add SslPolicy Field to FrontendConfig
  hack/update-codegen.sh
  pkg/apis/frontendconfig/v1beta1/types.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
  pkg/frontendconfig/client/clientset/versioned/clientset.go
  pkg/frontendconfig/client/clientset/versioned/doc.go
  pkg/frontendconfig/client/clientset/versioned/fake/clientset_generated.go
  pkg/frontendconfig/client/clientset/versioned/fake/doc.go
  pkg/frontendconfig/client/clientset/versioned/fake/register.go
  pkg/frontendconfig/client/clientset/versioned/scheme/doc.go
  pkg/frontendconfig/client/clientset/versioned/scheme/register.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/doc.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/doc.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/fake_frontendconfig.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/fake/fake_frontendconfig_client.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/frontendconfig.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/frontendconfig_client.go
  pkg/frontendconfig/client/clientset/versioned/typed/frontendconfig/v1beta1/generated_expansion.go
  pkg/frontendconfig/client/informers/externalversions/factory.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/interface.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/v1beta1/frontendconfig.go
  pkg/frontendconfig/client/informers/externalversions/frontendconfig/v1beta1/interface.go
  pkg/frontendconfig/client/informers/externalversions/generic.go
  pkg/frontendconfig/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/frontendconfig/client/listers/frontendconfig/v1beta1/expansion_generated.go
  pkg/frontendconfig/client/listers/frontendconfig/v1beta1/frontendconfig.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1027 Typesafe composite conversion
  pkg/composite/gen.go
  pkg/composite/gen/main.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
  pkg/healthchecks/healthchecks.go
  pkg/neg/types/mock.go
Labels: approved, cncf-cla: yes, size/XXL

#1026 Move apply probe to healthchecks package
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
Labels: approved, cncf-cla: yes, size/L

#1028 Reduce surface area of healthchecks
  pkg/backends/syncer.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecks/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1019 Implement SslPolicies for TargetHttpsProxy
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#991 Add a controller for handling L4 Internal LoadBalancer services
  cmd/glbc/main.go
  pkg/annotations/service.go
  pkg/backends/backends.go
  pkg/backends/features/features.go
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/controller/translator/translator.go
  pkg/firewalls/firewalls_l4.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/healthchecks/healthchecks_l4_test.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/fakes.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l7.go
  pkg/test/utils.go
  pkg/utils/common/finalizer.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/namer.go
  pkg/utils/patch.go
  pkg/utils/serviceport.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/BUILD
  vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/helpers.go
  vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1030 Fix backendconfig annotation key for beta
  cmd/e2e-test/affinity_test.go
  cmd/e2e-test/backend_config_test.go
  cmd/e2e-test/cdn_test.go
  cmd/e2e-test/customrequestheaders_test.go
  cmd/e2e-test/draining_test.go
  cmd/e2e-test/iap_test.go
  cmd/e2e-test/security_policy_test.go
  cmd/e2e-test/timeout_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1029 Set healthcheck from BackendConfig
  go.sum
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, size/XXL

#1023 Enable Access Logs by default
  pkg/backends/backends.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1035 Enable Access Logs by default
  go.mod
  go.sum
  pkg/backends/backends.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1022 Add deployment guide for GLBC in non-gcp mode.
  docs/deploy/gke/non-gcp/README.md
  docs/deploy/gke/non-gcp/default-http-backend.yaml
  docs/deploy/gke/non-gcp/gce.conf.temp
  docs/deploy/gke/non-gcp/generate.sh
  docs/deploy/gke/non-gcp/glbc.yaml
  docs/deploy/gke/non-gcp/rbac.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1036 Fix Access logs enable whitebox test
  pkg/fuzz/whitebox/num_backend_services.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1037 Bugfix: Fix frontend resource deletion test
  cmd/e2e-test/basic_test.go
  pkg/e2e/helpers.go
  pkg/fuzz/validator.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1040 Add feature flag `EnableBackendConfigHealthCheck`
  pkg/flags/flags.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1032 Split large file healthchecks.go => healthcheck.go,healthchecks.go
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1025 Add asm-ready as the status signal of asm mode.
  cmd/e2e-test/asm_test.go
  pkg/cmconfig/config.go
  pkg/cmconfig/config_test.go
  pkg/cmconfig/controller.go
  pkg/cmconfig/controller_test.go
  pkg/context/context.go
  pkg/e2e/helpers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1039 Add Access Log field to BackendConfig API
  go.sum
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/composite/gen.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
