Repository kubernetes/ingress-gce, pull requests merged in 2021-11, with the labels that each got.

#1599 Fix ports in L4NetLB
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4netlb.go
  pkg/test/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1600 Trigger sync for certain node changes
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/fakes.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1603 [Cherrypick #1600 into 1.13] Trigger sync for certain node changes
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/fakes.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1604 [Cherrypick #1600 into 1.12] Zone change 1.12
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/fakes.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1605 [Cherrypick #1600 into 1.11] Trigger sync for certain node changes
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/fakes.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1596 Implement delete function for L4NetLB
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4netlb/l4netlbcontroller.go
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/test/gcehooks.go
  pkg/test/utils.go
  pkg/utils/common/finalizer.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#1608 Allow users to specify resource url for the nat subnet
  pkg/apis/serviceattachment/v1/types.go
  pkg/apis/serviceattachment/v1beta1/types.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1609 [Cherrypick #1600 to 1.14] Trigger sync for certain node changes
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/fakes.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1611 [Cherrypick #1608 in 1.13] Allow users to specify resource url for the nat subnet
  pkg/apis/serviceattachment/v1beta1/types.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1610 [Cherrpick #1608 to 1.14] Allow users to specify resource url for the nat subnet
  pkg/apis/serviceattachment/v1beta1/types.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1612 PSC uses V1 ServiceAttachment
  pkg/backendconfig/backendconfig.go
  pkg/context/context.go
  pkg/crd/crd.go
  pkg/crd/crd_test.go
  pkg/crd/meta.go
  pkg/e2e/adapter/psc.go
  pkg/e2e/adapter/psc_test.go
  pkg/e2e/fixtures.go
  pkg/e2e/framework.go
  pkg/e2e/helpers.go
  pkg/experimental/workload/workload.go
  pkg/frontendconfig/frontendconfig.go
  pkg/ingparams/ingparams.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
  pkg/serviceattachment/serviceattachment.go
  pkg/svcneg/svcneg.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1588 Add Rbs mode flag
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/flags/l4netlbrbsmode.go
  pkg/flags/l4netlbrbsmode_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1607 Update L4NetLB services
  pkg/l4/l4controller.go
  pkg/l4netlb/l4netlbcontroller.go
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/test/gcehooks.go
  pkg/test/utils.go
  pkg/utils/loadbalancers/ports.go
  pkg/utils/loadbalancers/ports_test.go
Labels: cncf-cla: yes, lgtm, size/XL, needs-ok-to-test, approved

#1387 Add missing CDN config options
  cmd/e2e-test/cdn_test.go
  docs/deploy/gke/gke-self-managed.sh
  docs/deploy/resources/glbc.yaml
  docs/deploy/resources/rbac.yaml
  go.mod
  go.sum
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/backendconfig/validation.go
  pkg/backendconfig/validation_test.go
  pkg/backends/backends.go
  pkg/backends/features/cdn.go
  pkg/backends/features/cdn_test.go
  pkg/backends/interfaces.go
  pkg/backends/syncer.go
  pkg/composite/composite.go
  pkg/composite/gen.go
  pkg/composite/gen/main.go
  pkg/composite/gen_test.go
  pkg/composite/meta/meta.go
  pkg/e2e/adapter/beconfig.go
  pkg/e2e/framework.go
  pkg/fuzz/helpers.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1615 Exclude nodes that have GKE drain operation label, from LB backends.
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/types/fakes.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1617 [1.14] Exclude nodes that have GKE drain operation label, from LB backends.
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/types/fakes.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1606 Unified health check description for ILB and XLB resource
  pkg/backends/backends.go
  pkg/firewalls/firewalls_l4.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/healthchecks/healthchecks_l4_test.go
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1619 Add back original CDN test for older Ingress Versions
  cmd/e2e-test/cdn_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1620 Change ExpandedCDN to Cdn
  cmd/e2e-test/cdn_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1624 Revert "Merge pull request #1606 from kl52752/healthCheckFix"
  pkg/backends/backends.go
  pkg/firewalls/firewalls_l4.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/healthchecks/healthchecks_l4_test.go
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, needs-ok-to-test, approved

#1614 Add NetLB service annotations
  pkg/l4/l4controller.go
  pkg/l4netlb/l4netlbcontroller.go
  pkg/l4netlb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/loadbalancers/l4annotations.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
