Repository kubernetes/ingress-gce, pull requests merged in 2021-08, with the labels that each got.

#1527 Add ability to change max rps/endpoint and capacity scaler
  go.sum
  pkg/backends/ig_linker.go
  pkg/backends/ig_linker_test.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/flags/flags.go
  pkg/utils/gceurlmap_test.go
  pkg/utils/serviceport.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1528 Rename TrafficPolicy to TrafficScaling to avoid conflict with k8s.Ser…
  pkg/backends/ig_linker_test.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/flags/flags.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1530 Update Backends if the settings change w/ same Backends
  hack/run-local-glbc.sh
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1538 Always enable pathtype
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1536 Check for v1 IngressClass resource
  cmd/glbc/app/init.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1539 [1.13] Allow Unschedulable nodes to be part of the LB backends list
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1541 [Cherrypick #1538] Always enable pathtype into release 1.13
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1542 [Cherrypick #1536] Check for v1 IngressClass resource into release-1.13
  cmd/glbc/app/init.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1540 [1.12] Allow Unschedulable nodes to be part of the LB backends list.
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1522 Implement flag-gated support for Endpoint Slices in the NEG controller.
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/testing.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
  pkg/utils/endpointslices/utils.go
  pkg/utils/endpointslices/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1543 Skip unsupported healths during NEG polling
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1544 [Cherrypick #1543] Skip unsupported healths during NEG polling
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1532 Remove nodes from LocalTrafficPolicy NEG if they are not a ready candidate
  pkg/neg/controller.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1545 Mitigate race condition between service controller and subsetting controller for existing services.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1548 [1.13] Mitigate race condition between service controller and subsetting controller for existing services.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1549 [1.13] Remove nodes from LocalTrafficPolicy NEG if they are not a ready candidate
  pkg/neg/controller.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1550 Fix comment for ep calculator test - local mode
  pkg/neg/syncers/endpoints_calculator_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1552 Skip processing non-ILB services in NEG controller.
  pkg/l4/l4controller.go
  pkg/neg/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1553 [1.13] Skip processing non-ILB services in NEG controller.
  pkg/l4/l4controller.go
  pkg/neg/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1555 [1.13] Only skip ILB processing if legacy ILB FR is found.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1554 Only skip ILB processing if legacy ILB FR is found.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1557 Support EndpointSlices in the controller/translator.
  pkg/context/context.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1556 Small fixes for PR 1522
  pkg/neg/controller_test.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/types/types.go
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
