Repository kubernetes/ingress-gce, pull requests merged in 2021-06, with the labels that each got.

#1452 Do not process status only updates
  pkg/psc/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1464 Update k8s-cloud-provider to 1.16
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/service.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/openapiv2/OpenAPIv2.proto
  vendor/github.com/googleapis/gnostic/openapiv2/README.md
  vendor/github.com/googleapis/gnostic/openapiv2/openapi-2.0.json
  vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XL

#1465 fix should process conditions
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1470 Convert old ingress properly
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1472 [Cherrypick #1470] into release-1.12: Process service if old ingress class was glbc
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1474 Use PSC Beta APIs
  pkg/e2e/helpers.go
  pkg/fuzz/gcp.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1473 Use PSC v1beta1 API
  hack/update-codegen.sh
  pkg/apis/serviceattachment/v1alpha1/doc.go
  pkg/apis/serviceattachment/v1alpha1/register.go
  pkg/apis/serviceattachment/v1alpha1/types.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
  pkg/context/context.go
  pkg/e2e/fixtures.go
  pkg/e2e/helpers.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
  pkg/serviceattachment/client/clientset/versioned/clientset.go
  pkg/serviceattachment/client/clientset/versioned/fake/clientset_generated.go
  pkg/serviceattachment/client/clientset/versioned/fake/register.go
  pkg/serviceattachment/client/clientset/versioned/scheme/register.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/doc.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/doc.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/fake_serviceattachment.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/fake/fake_serviceattachment_client.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/generated_expansion.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/serviceattachment.go
  pkg/serviceattachment/client/clientset/versioned/typed/serviceattachment/v1alpha1/serviceattachment_client.go
  pkg/serviceattachment/client/informers/externalversions/generic.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/interface.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/v1alpha1/interface.go
  pkg/serviceattachment/client/informers/externalversions/serviceattachment/v1alpha1/serviceattachment.go
  pkg/serviceattachment/client/listers/serviceattachment/v1alpha1/expansion_generated.go
  pkg/serviceattachment/client/listers/serviceattachment/v1alpha1/serviceattachment.go
  pkg/serviceattachment/serviceattachment.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1482 ILB metrics cherrypick into 1.12
  pkg/annotations/service.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/l4/metrics/metrics.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/metrics/metrics.go
  pkg/test/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1477 Add push-multiarch rule to push multiarch images (docker manifest list)
  build/rules.mk
Labels: approved, cncf-cla: yes, lgtm, size/S

#1483 Log fix cherrypick into 1.12
  pkg/l4/l4controller.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1485 avoid panic when reflector under load and rate limited
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1484 Cherrypick L4 status/annotation reset order change into 1.12
  pkg/l4/l4controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1487 [Cherrypick #1485 into release-1.12] avoid panic when reflector under load and rate limited
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1488 [Cherrypick #1485 into release-1.11] avoid panic when reflector under load and rate limited
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1479 Emit total number of services metrics
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/psc/controller.go
  pkg/psc/metrics/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1489 Add rate limiting scaling parameter
  pkg/flags/flags.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1490 Cherrypick: Add rate limiting scaling parameter
  pkg/flags/flags.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1491 Cherrypick: Add rate limiting scaling parameter
  pkg/flags/flags.go
  pkg/ratelimit/ratelimit.go
  pkg/ratelimit/ratelimit_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1480 Use the new ServiceAttachment fields over deprecated ones
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1493 Wrap errors using '%w' in the format strings
  pkg/psc/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1492 Update Ingress Sync Queue to use multiple workers
  pkg/controller/controller.go
  pkg/flags/flags.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1495 Cherry-pick #1492 [Update Ingress Sync Queue to use multiple workers] into release-1-12
  pkg/controller/controller.go
  pkg/flags/flags.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1496 Cherry-pick #1492 [Update Ingress Sync Queue to use multiple workers] into release-1-11
  pkg/controller/controller.go
  pkg/flags/flags.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1494 Filter errors when marking sync failures for metrics
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1475 Only bump LastModifiedTimestamp for Status updates
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1476 Process Accept and Reject lists for ServiceAttachment
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1499 Add standard k8s resource description for ServiceAttachments
  pkg/context/context.go
  pkg/flags/flags.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
  pkg/utils/descutils/utils.go
  pkg/utils/descutils/utils_test.go
  pkg/utils/serviceattachment/svcattachmentdesc.go
  pkg/utils/serviceattachment/svcattachmentdesc_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1500 Emit success event after Service Attachment creation
  pkg/psc/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
