Repository kubernetes/ingress-gce, pull requests merged in 2021-09, with the labels that each got.

#1529 skip NEG API call for NEG linker if possible
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/controller/controller.go
  pkg/l4/l4controller.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1551 Add e2e test to validate consistency between v1 and v1beta1 Backendconfig APIs
  cmd/e2e-test/backend_config_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1564 Look for UPGRADE_NODES annotation only for ILB Subsetting.
  pkg/neg/controller.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1565 Add a lock for the recorders map.
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1566 [1.13] Look for UPGRADE_NODES annotation only for ILB Subsetting.
  pkg/neg/controller.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1567 [1.13] Add a lock for the recorders map.
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1563 Add component version metric
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1562 Add errors to healthcheck merge() func
  pkg/backends/integration_test.go
  pkg/backends/syncer_test.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/translator/healthchecks.go
  pkg/translator/healthchecks_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1569 add OWNERS file in apis subpackage
  pkg/apis/OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1561 Fix bug with gathering ports for NEG.
  cmd/glbc/app/init.go
  pkg/backends/neg_linker_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/syncer_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1568 reorder lock vars to prefix the map they guard.
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1571 [1.12] Prevent race conditions between service and subsetting controllers.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1570 [1.11] Prevent race conditions between service and subsetting controllers.
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1572 Process ILB service when NEG annotation changes.
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/l4/l4controller.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1575 Skip using deprecated zone label for Nodes.
  docs/deploy/gke/non-gcp/README.md
  pkg/annotations/ingress.go
  pkg/e2e/fixtures.go
  pkg/test/utils.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1534 Include zones with unready nodes when listing zones.
  pkg/controller/controller.go
  pkg/controller/translator/translator.go
  pkg/controller/utils_test.go
  pkg/instances/fakes.go
  pkg/instances/instances.go
  pkg/instances/interfaces.go
  pkg/l4/l4controller.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/simple_zone_getter.go
  pkg/neg/types/simple_zone_getter_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1577 Updates E2E test images registry
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
