Repository kubernetes/ingress-gce, pull requests merged in 2021-07, with the labels that each got.

#1451 Process updates to ServiceAttachment spec
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1509 Add debug GC log lines during Ingress sync
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1511 add lock to GC logic
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1505 Drop k8s.io/kubernetes import
  go.mod
  go.sum
  pkg/firewalls/firewalls_test.go
  pkg/l4/l4controller.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/psc/controller.go
  pkg/utils/common/common_test.go
  pkg/utils/common/finalizer.go
  pkg/utils/patch/patch_test.go
  pkg/utils/slice/slice.go
  pkg/utils/slice/slice_test.go
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1507 Update instructions to test ingress-gce locally.
  docs/contrib/cluster-setup.md
  hack/setup-local.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1512 Cherrypick #1407[Update v1beta1 Security Policy Config for Open API gen] into release 1.11
  go.sum
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/backendconfig/client/clientset/versioned/clientset.go
  pkg/backendconfig/client/clientset/versioned/doc.go
  pkg/backendconfig/client/clientset/versioned/fake/clientset_generated.go
  pkg/backendconfig/client/clientset/versioned/fake/doc.go
  pkg/backendconfig/client/clientset/versioned/fake/register.go
  pkg/backendconfig/client/clientset/versioned/scheme/doc.go
  pkg/backendconfig/client/clientset/versioned/scheme/register.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/backendconfig_client.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/doc.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/fake/doc.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/fake/fake_backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/fake/fake_backendconfig_client.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1/generated_expansion.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/backendconfig_client.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/doc.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/fake/doc.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/fake/fake_backendconfig.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/fake/fake_backendconfig_client.go
  pkg/backendconfig/client/clientset/versioned/typed/backendconfig/v1beta1/generated_expansion.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/interface.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1/backendconfig.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1/interface.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1beta1/backendconfig.go
  pkg/backendconfig/client/informers/externalversions/backendconfig/v1beta1/interface.go
  pkg/backendconfig/client/informers/externalversions/factory.go
  pkg/backendconfig/client/informers/externalversions/generic.go
  pkg/backendconfig/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/backendconfig/client/listers/backendconfig/v1/backendconfig.go
  pkg/backendconfig/client/listers/backendconfig/v1/expansion_generated.go
  pkg/backendconfig/client/listers/backendconfig/v1beta1/backendconfig.go
  pkg/backendconfig/client/listers/backendconfig/v1beta1/expansion_generated.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1510 [Cherrypick #1509] Add debug GC log lines during Ingress sync
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1513 [Cherrpick #1511] Add lock to GC into release-1.13
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1517 Enqueue Node updates to VM_IP_NEG controller.
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/subsets.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1518 [1.13] Enqueue Node updates to VM_IP_NEG controller
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/subsets.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1521 Add comment to ILB nodes test, remove extra sleep.
  pkg/neg/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1520 [1.11] Enqueue Node updates to VM_IP_NEG controller
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/subsets.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1519 [1.12] Enqueue Node updates to VM_IP_NEG controller.
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/subsets.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1516 Fix err msg
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1524 Use local method to get instance references
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1525 [Cherrypick #1524] Instance url fix remove 1.13
  pkg/instances/instances.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1523 Updated the value of LabelNodeRoleExcludeBalancer to the V1 string.
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1526 [1.13] Updated the value of LabelNodeRoleExcludeBalancer to the V1 string
  pkg/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S
