Repository kubernetes/ingress-gce, pull requests merged in 2021-05, with the labels that each got.

#1427 Populate namespace when creating ingress
  cmd/e2e-test/customrequestheaders_test.go
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1152 Fix ensure logging workflow for nil/empty sampling rate
  pkg/backends/features/logging.go
  pkg/backends/features/logging_test.go
  pkg/composite/gen.go
  pkg/composite/gen/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1428 Populate Namespace on ingresses in ILB E2E
  cmd/e2e-test/ilb_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1429 Use %w to wrap errors.
  pkg/backends/backends.go
  pkg/backends/ig_linker.go
  pkg/backends/syncer.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4/l4controller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1430 retrieve NEG endpoints before getting the wanted Endpoints
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1432 [Cherrypick #1410] retrieve NEG endpoints before getting the wanted Endpoints into release-1.10
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1431 [Cherrypick #1410] retrieve NEG endpoints before getting the wanted Endpoints into release 1.11
  pkg/neg/syncers/transaction.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1434 Add PSC Usage and Controller metrics
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/psc/controller.go
  pkg/psc/metrics/metrics.go
  pkg/psc/metrics/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1439 [Cherrypick #1434] PSC Usage and Internal Metrics to 1.11
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/psc/controller.go
  pkg/psc/metrics/metrics.go
  pkg/psc/metrics/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1440 [Cherrypick #1434] PSC Usage and Internal Metrics to 1.12
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/psc/controller.go
  pkg/psc/metrics/metrics.go
  pkg/psc/metrics/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1436 Add a new L4 ILB metric for sync errors
  pkg/annotations/service.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/l4/metrics/metrics.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/metrics/metrics.go
  pkg/test/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1437 Generate URL for GCE instances resource
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/instances/instances.go
  pkg/instances/instances_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1441 Add ProxyProtocol to Service Attachment Spec
  pkg/apis/serviceattachment/v1alpha1/types.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1412 Cherrypick l4 test timeout fix.
  pkg/l4/l4controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1442 Cherrypick PR#1429 - Use %w to wrap errors.
  pkg/backends/backends.go
  pkg/backends/ig_linker.go
  pkg/backends/syncer.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4/l4controller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1443 Cherrypick PR#1436 - Add a new L4 ILB metric for sync errors.
  pkg/annotations/service.go
  pkg/l4/l4controller.go
  pkg/l4/l4controller_test.go
  pkg/l4/metrics/metrics.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/metrics/metrics.go
  pkg/test/utils.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1444 Fix log message/comment.
  pkg/l4/l4controller.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1445 Cherrypick of log fix
  pkg/l4/l4controller.go
  pkg/loadbalancers/forwarding_rules.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1448 Fix duplicate service ports sync
  pkg/utils/gceurlmap.go
  pkg/utils/gceurlmap_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1449 Fix adapter client patch
  pkg/e2e/adapter/ingress.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1446 Update Consumer Forwarding Rules in Status
  pkg/apis/serviceattachment/v1alpha1/types.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1450 Add lastSyncTimestamp json tag
  pkg/apis/serviceattachment/v1alpha1/types.go
  pkg/apis/serviceattachment/v1alpha1/zz_generated.openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1456 Process service if old ingress class was glbc
  pkg/neg/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1454 Switch the order of L4 service status reset and annotations reset.
  pkg/l4/l4controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1453 Add omitempty tag for ConsumerForwardingRules
  pkg/apis/serviceattachment/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1457 Switch the order of L4 service status reset and annotations reset.
  pkg/l4/l4controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1458 stop periodic resync on endpoints object
  pkg/context/context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1460 [Cherrypick #1458 into release-1.11]stop periodic resync on endpoints object
  pkg/context/context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1455 Add prameshj and swetharepakula into the OWNER file
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1459 [Cherrypick #1458 into release-1.12] stop periodic resync on endpoints object
  pkg/context/context.go
Labels: approved, cncf-cla: yes, lgtm, size/S
