Repository kubernetes/ingress-gce, pull requests merged in 2022-09, with the labels that each got.

#1798 Fix typo NewL4SynResult -> NewL4SyncResult
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1799 Remove duplicate code
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1800 Fix deleting address in RBS
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1797 Use ForwardingRulesProvider, instead of composite.Delete, on deleting L4 Forwarding Rules
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1801 fix typo in instruction
  cmd/e2e-test/readme.md
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1769 Add golang-ci with errcheck enabled to test suite to ensure all errors produced are checked
  .golangci.yaml
  build/test.sh
  cmd/echo/app/handlers.go
  cmd/echo/app/tls.go
  cmd/glbc/app/handlers.go
  cmd/glbc/main.go
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/composite/meta/meta.go
  pkg/e2e/helpers.go
  pkg/firewalls/controller.go
  pkg/loadbalancers/address_manager.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1795 Update e2e-test README
  cmd/e2e-test/readme.md
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1802 Reformat forwarding rules provider
  pkg/forwardingrules/forwarding_rules.go
  pkg/forwardingrules/forwarding_rules_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1763 Create Health Checks Provider to interact with Google Cloud
  cmd/glbc/main.go
  pkg/healthchecks/interfaces.go
  pkg/healthchecksl4/healthchecksl4.go
  pkg/healthchecksl4/healthchecksl4_test.go
  pkg/healthchecksl4/interfaces.go
  pkg/healthchecksprovider/healthchecksprovider.go
  pkg/healthchecksprovider/healthchecksprovider_test.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#1804 Refactor l4_test assertion function
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1805 Refactor l4_test assertInternalLbResourcesDeleted function
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1806 Add L4Firewall to namer, instead of using L4Backend
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1809 remove rramkumar1 from owners
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1808 Refactor healthchecksl4, change functions order, rename functions
  pkg/healthchecksl4/healthchecksl4.go
  pkg/healthchecksl4/interfaces.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1811 Remove go test command with -i flag, cause it was deprecated
  build/test.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1813 Fix errcheck linter for all non-test files
  .golangci.yaml
  cmd/404-server-with-metrics/server-with-metrics.go
  cmd/echo/app/handlers.go
  cmd/fuzzer/fuzzer.go
  cmd/glbc/app/handlers.go
  cmd/workload-daemon/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1815 Log if health check intended shared on deletion
  pkg/healthchecksl4/healthchecksl4.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1810 Add checking for firewall source ranges in l4_test
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1814 Fix deletion of address in l4
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1817 Small refactor of l4controller_test assertions
  pkg/l4lb/l4controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1776 Add Custom response header e2e test
  cmd/e2e-test/customresponseheaders_test.go
  pkg/fuzz/helpers.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1824 Add a new NetL4LB flag
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/flags/flags.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1822 Refactor l4 tests
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/loadbalancers/l4testutils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1820 Create struct argument L4NetLBParams for L4NetLB constructor
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved
