Repository kubernetes/ingress-gce, pull requests merged in 2022-01, with the labels that each got.

#1645 [Cherrypick #1644 to 1.14] do not remove NEG from backend service when cluster shrinks
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1636 Add Network Tier support to L4 NetLB
  pkg/annotations/service.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/address_manager.go
  pkg/loadbalancers/address_manager_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/test/gcehooks.go
  pkg/test/utils.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1647 Extract common parts for L4 LoadBalancers - Part 3
  pkg/firewalls/firewalls_l4.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1649 Add instance group management enabling flags
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1650 Fix a bug where beta/v1/alpha NEG url are consisdered different
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1653 avoid updating BackendService if possible
  pkg/backends/neg_linker.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1651 add zone parameter into instance-group gcloud command in setup-local script
  hack/setup-local.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1654 [Cherrypick #1653 into release-1.15] avoid updating BackendService if possible
  pkg/backends/neg_linker.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1655 [Cherrypick #1650 #1653 into release-1.14] Fix a bug where beta/v1/alpha NEG url are consisdered different
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1658 Change l4elb-rbs-mode flag to simple boolean flag run-l4-netlb-controller
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/flags/l4netlbrbsmode.go
  pkg/flags/l4netlbrbsmode_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1660 Fix unhandled err variable
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1662 [Cherrypick #1660 into release-1.15] Fix unhandled err variable
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1661 [Cherrypick #1660 into release-1.14] Fix unhandled err variable
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/S, approved
