Repository kubernetes/ingress-gce, pull requests merged in 2022-06, with the labels that each got.

#1724 Fix last error logging in affinity tests
  cmd/e2e-test/affinity_beta_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1725 Add backend service name into affinity check error
  cmd/e2e-test/affinity_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1726 Add new members to OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1729 Use discovery/v1 EndpointSlice
  pkg/context/context.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/experimental/workload/controller.go
  pkg/experimental/workload/controller_test.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/testing.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
  pkg/utils/endpointslices/utils.go
  pkg/utils/endpointslices/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1728 Init first sync error time with transation start time
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/metrics/types.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1731 Add new members to OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1703 corrected link for gke-self-managed.sh
  docs/deploy/gke/README.md
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1736 [Cherrypick #1733 into release-1.15] Do not return error if EndpointSlicesServiceKey func errors
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1737 [Cherrypick #1733 into release-1.14] Do not return error if EndpointSlicesServiceKey func errors
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1735 [Cherrypick #1733 into release-1.16] Do not return error if EndpointSlicesServiceKey func errors
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1734 [Cherrypick #1733 in release-1.17] Do not return error if EndpointSlicesServiceKey func errors
  pkg/utils/endpointslices/index.go
  pkg/utils/endpointslices/index_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1739 Extend transition timeout to 15 min
  cmd/e2e-test/affinity_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1741 Fix preventTargetPoolToRBSMigration. Properly delete annotation
  pkg/l4lb/l4lbcommon.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/test/gcehooks.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1742 Handle L4 ELB RBS controller race with legacy on service creation
  pkg/firewalls/firewalls_l4.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4lbcommon.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/l4lb/metrics/metrics.go
  pkg/loadbalancers/l4syncresult.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1743 Delete RBS annotations as a last step on garbage collection
  pkg/l4lb/l4netlbcontroller.go
Labels: cncf-cla: yes, lgtm, size/S, approved
