Repository kubernetes/ingress-gce, pull requests merged in 2022-10, with the labels that each got.

#1821 Use namer.L4Firewall and namer.L4Backend instead of servicePort
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1818 Fix L4 Premium Network Tier metric, fix comments
  pkg/metrics/features.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1807 Add Ingress Support for L7-ILB HTTP+HTTPS on same LB
  cmd/e2e-test/ilb_test.go
  pkg/e2e/fixtures.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/loadbalancers_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1812 Change healthchecksl4 sync mechanism
  cmd/glbc/main.go
  pkg/healthchecksl4/healthchecksl4.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1828 Change l4 healthcheck timeout
  pkg/healthchecksl4/healthchecksl4.go
  pkg/healthchecksl4/healthchecksl4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1829 Delete L4LB healthcheck test
  pkg/healthchecksl4/healthchecksl4_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1830 Add more L4 latency metrics
  pkg/l4lb/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1831 [Cherrypick #1828] l4 healthcheck timeouts change
  pkg/healthchecks/healthchecks_l4.go
  pkg/healthchecks/healthchecks_l4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1837 Fix ports read/write races in neg tests
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1833 increase test coverage
  pkg/healthchecksl4/healthchecksl4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1782 Add Dual-Stack support to L4 ILB
  cmd/glbc/main.go
  pkg/annotations/service.go
  pkg/context/context.go
  pkg/firewalls/firewalls_l4.go
  pkg/flags/flags.go
  pkg/healthchecksl4/healthchecksl4.go
  pkg/healthchecksl4/healthchecksl4_test.go
  pkg/healthchecksl4/interfaces.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4lbcommon.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/forwarding_rules_ipv6_test.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/loadbalancers/l4syncresult.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/url_maps.go
  pkg/test/utils.go
  pkg/utils/ipfamily.go
  pkg/utils/ipfamily_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1845 Add more logs to L4 NetLB
  pkg/backends/backends.go
  pkg/backends/regional_ig_linker_test.go
  pkg/healthchecksl4/healthchecksl4.go
  pkg/instances/instances.go
  pkg/l4lb/l4lbcommon.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1844 Add statusCodeHandler to 404-server-with-metrics which serves status code given in URL path
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1846 [Cherrypick #1844] cherry pick 404-server-with-metrics change to release 1.20
  cmd/404-server-with-metrics/server-with-metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1847 Remove emitting Update event on top-level in L4 NetLB
  pkg/l4lb/l4netlbcontroller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1850 Add more logs to L4 controllers
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved
