Repository kubernetes/ingress-gce, pull requests merged in 2022-08, with the labels that each got.

#1760 Update the generated code
  pkg/apis/backendconfig/v1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/apis/backendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.deepcopy.go
  pkg/apis/frontendconfig/v1beta1/zz_generated.openapi.go
  pkg/apis/ingparams/v1beta1/zz_generated.deepcopy.go
  pkg/apis/ingparams/v1beta1/zz_generated.openapi.go
  pkg/apis/serviceattachment/v1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1/zz_generated.openapi.go
  pkg/apis/serviceattachment/v1beta1/zz_generated.deepcopy.go
  pkg/apis/serviceattachment/v1beta1/zz_generated.openapi.go
  pkg/apis/svcneg/v1beta1/zz_generated.deepcopy.go
  pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1747 Add minor logs to track processing track for neg controller
  pkg/neg/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1774 Fix RBS crash, when getting NodePorts for Services without ports
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1775 [Cherrypick #1774 in release-1.19] Fix RBS crash, when getting NodePorts for Services without ports
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1749 Fix BackendConfig.securityPolicy is not removed after config updates
  pkg/backends/features/securitypolicy.go
  pkg/backends/features/securitypolicy_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1778 [Cherrypick #1748 to release-1.19] Fix DestinationRanges update when IP changes
  pkg/firewalls/firewalls_l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1780 ConfigMap informer should only watch --asm-configmap-based-config-nam…
  pkg/cmconfig/controller.go
  pkg/context/context.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1750 Migrate gce-ingress to LeasesResourceLock from ConfigMapsLeases
  cmd/glbc/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1771 Add Changes for Custom Response Header API
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.deepcopy.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1777 Increase timeouts to reflect GCE API
  cmd/e2e-test/draining_test.go
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1764 Split GetPortsAndProtocol function to 4 separate functions
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1759 Create Forwarding Rules provider
  pkg/forwardingrules/forwarding_rules.go
  pkg/forwardingrules/forwarding_rules_test.go
  pkg/l4lb/intefaces.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/golang.org/x/xerrors/LICENSE
  vendor/golang.org/x/xerrors/PATENTS
  vendor/golang.org/x/xerrors/README
  vendor/golang.org/x/xerrors/adaptor.go
  vendor/golang.org/x/xerrors/codereview.cfg
  vendor/golang.org/x/xerrors/doc.go
  vendor/golang.org/x/xerrors/errors.go
  vendor/golang.org/x/xerrors/fmt.go
  vendor/golang.org/x/xerrors/format.go
  vendor/golang.org/x/xerrors/frame.go
  vendor/golang.org/x/xerrors/go.mod
  vendor/golang.org/x/xerrors/internal/internal.go
  vendor/golang.org/x/xerrors/wrap.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1781 cleanup l4 tests
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1787 Extract NewL4 arguments into params struct
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1788 Create getSubnetworkURLByName to refactor part of the L4 code
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1786 Extract to separate function L4HealthCheckFirewall from L4 namer L4HealthCheck
  pkg/healthchecks/healthchecks_l4.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1789 Rename *L4 method receivers from l -> l4
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1790 Refactor L4 Namer, add getSuffixedName, getTrimmedNamespacedName function
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/neg/types/types.go
  pkg/utils/namer/interfaces.go
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
  pkg/utils/namer/namer.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1791 Cleanup code
  pkg/backends/ig_linker.go
  pkg/backends/neg_linker.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/neg/syncers/transaction.go
  pkg/ratelimit/ratelimit.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#1754 Fix creation of NEGs in the new zone when cluster spans to the new zone
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/types.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1772 Add Custom Response Header Logic and the Unit Tests for it
  pkg/backends/features/customresponseheaders.go
  pkg/backends/features/customresponseheaders_test.go
  pkg/backends/syncer.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1701 updated changelog
  CHANGELOG.md
Labels: cncf-cla: yes, size/L, lgtm, approved
