Repository kubernetes/ingress-gce, pull requests merged in 2022-12, with the labels that each got.

#1871 Fixes subnet in e2e test command
  cmd/e2e-test/run.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1880 Change e2e regional address to use full subnet path
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1881 NetLB controller: cleanup RBS resources in case service type changed
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1879 Fix L4 NetLB RBS cleanup when Service Type changed
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, size/M, do-not-merge/hold, approved

#1885 [Cherrypick #1879] cherry pick service type transision fix to release 1.20
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1888 Revert "Don't log all node names"
  pkg/instancegroups/manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1890 NetLB: Treat LoadBalancer IP setup errors as user errors.
  pkg/loadbalancers/address_manager.go
  pkg/loadbalancers/address_manager_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/test/gcehooks.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
