Repository kubernetes/ingress-gce, pull requests merged in 2023-03, with the labels that each got.

#1978 run e2e tests
  hack/boskos.sh
  hack/run-e2e-gce.sh
Labels: cncf-cla: yes, size/L, lgtm, approved

#1967 Replace fetch from apiserver with informer cache while processing SvcNeg
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1981 Add smaller bucket sizes for workqueue metrics
  pkg/metrics/workqueue.go
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#1985 Add flag for Transparent Health Check
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1989 Replace k8s.gcr.io references with registry.k8s.io
  CHANGELOG.md
  docs/deploy/gke/README.md
  docs/deploy/gke/csm/default-http-backend.yaml
  docs/deploy/gke/csm/glbc.yaml
  docs/deploy/gke/non-gcp/default-http-backend.yaml
  docs/deploy/gke/non-gcp/glbc.yaml
  docs/deploy/resources/default-http-backend.yaml
  docs/troubleshooting/troubleshooting.md
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1943 Export various stats about services in the metrics exported by this c…
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/servicemetrics/servicemetrics.go
  pkg/servicemetrics/servicemetrics_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1986 Fix log wrong format argument
  pkg/healthchecksl4/healthchecksl4.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1960 Create GKE diagnoser command base and update vendor
  cmd/gke-diagnoser/app/command/root.go
  cmd/gke-diagnoser/main.go
  go.mod
  go.sum
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/CONDUCT.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/active_help.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1976 Concurrently process deletion candidates within NEG Garbage Collector
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/testing.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1988 Add type PodLabelPropagationConfig structs
  pkg/neg/types/types.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1952 Create skeleton code for degraded mode procedure
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1983 Refactor error state checking
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/sync_results.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1992 Fix error caused by unhashable error list
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1993 Create the flag for degraded mode
  pkg/flags/flags.go
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1958 Filter terminal pods in degraded mode
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved

#1962 Filter pods from non-existent node in degraded mode
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1997 [Cherry pick #1973] Only use endpoint slices to generate network endpoints
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#1999 [Cherry pick #1972] Add names to queues used inside the NEG controller for enabling queue metrics
  pkg/neg/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2001 [Cherry pick #1967] Replace fetch from apiserver with informer cache while processing SvcNeg
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#1994 Update duplicate endpoint handling
  pkg/neg/syncers/utils.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2000 [Cherry pick #1981] Add smaller bucket sizes for workqueue metrics
  pkg/metrics/workqueue.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2002 [Cherry pick #1976] Concurrently process deletion candidates within NEG Garbage Collector
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/types/testing.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2006 Fix PublishL4NetLBDualStackSyncLatency
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2008 Adjust health check Description when BackendConfig used
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks_test.go
  pkg/translator/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1995 Add flag enable-label-propagation for label propagation feature
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2012 Process IPv6 Endpoints
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2017 Add Entry Point for LabelPropagationConfig and change tests related to that
  cmd/glbc/main.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved

#1965 Introduce rate limiter latency metrics
  pkg/ratelimit/metrics/metrics.go
  pkg/ratelimit/ratelimit.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2024 [Cherry-pick #2012 to 1.22] Process all endpoints and allow endpoint calculators to filter
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2014 Add code-elinka to the owners list
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2011 [Cherry-Pick 1.22] Fix PublishL4NetLBDualStackSyncLatency
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2036 Add Observe() func to internal GCERateLimiter
  pkg/ratelimit/ratelimit.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#1991 Bump k8s-cloud-provider to v1.22.0
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/context.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gce_projects.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/meta.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/observe.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/ratelimit.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/utils.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#2018 Flag for changes regarding health checks with BackendConfig
  pkg/flags/flags.go
  pkg/healthchecks/healthcheck.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/translator/healthchecks.go
  pkg/utils/healthchecks.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2037 Change e2e-test.yaml to support ARM
  cmd/e2e-test/e2e-test.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2042 Add comparing PortRange in forwarding rules Equal function
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2038 Set the k8s-cloud-provider API domain
  cmd/glbc/main.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2045 Refactor code related to PodLabelPropagationConfig
  cmd/glbc/main.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/labels/labels.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2051 Fix syncLock
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2053 [Cherry pick #2051] Fix syncLock deadlock
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2052 Update set error state for CalculateEndpoints()
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2054 Change diffBackends for NEG to not compare the API versions.
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test
