Repository kubernetes/ingress-gce, pull requests merged in 2023-07, with the labels that each got.

#2186 Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2187 Cherry-pick #2186: Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2188 [Cherry-pick #2186] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when ge…
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2181 Update healthcheck Description on BackendConfig removal
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2191 [Cherry-pick #2042] Add comparing PortRange in forwarding rules Equal function
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2184 Add instructions for check-gke-ingress and updated makefile
  Makefile
  build/build.sh
  build/rules.mk
  cmd/check-gke-ingress/README.md
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2194 Flag for THC port
  pkg/controller/controller.go
  pkg/firewalls/controller.go
  pkg/firewalls/controller_test.go
  pkg/flags/flags.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/translator/healthchecks.go
  pkg/translator/healthchecks_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved

#2193 Update Changelog for tags 1.16 to 1.24
  CHANGELOG.md
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2180 Add explicit verification for External/Internal IPv6 subnet
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/loadbalancers/l4netlbipv6.go
  pkg/test/utils.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2164 Add support for static DualStack IPs
  pkg/annotations/l4_static_address.go
  pkg/annotations/l4_static_address_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2195 Add metrics for Transparent Health Checks
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2175 Strong Session Affinity for L4NetLB
  cmd/glbc/main.go
  pkg/annotations/service.go
  pkg/annotations/service_test.go
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/regional_ig_linker_test.go
  pkg/context/context.go
  pkg/flags/flags.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#2200 Populate IdleTimeout for L4NetLB Session Affinity
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2199 Move L4 metrics related code to a separate file
  pkg/metrics/l4_metrics.go
  pkg/metrics/l4_metrics_test.go
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2204 Revert "[Cherry-pick #2186 -> 1.22] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY..."
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2205 Revert "[Cherry-pick #2186 -> 1.21] Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when ge…"
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2206 Revert "Cherry-pick #2186 -> 1.20: Include proxy-only subnet with purpose=REGIONAL_MANAGED_PROXY when generating firewall rules for Ingress"
  pkg/loadbalancers/features/l7ilb.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2202 Revert fix for issue #1706
  pkg/backends/features/securitypolicy.go
  pkg/backends/features/securitypolicy_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2213 Cherry pick 1.23
  pkg/backends/features/securitypolicy.go
  pkg/backends/features/securitypolicy_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2212 Cherry pick 1.20
  pkg/backends/features/securitypolicy.go
  pkg/backends/features/securitypolicy_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2214 Cherry pick 1.24
  pkg/backends/features/securitypolicy.go
  pkg/backends/features/securitypolicy_test.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2196 Improve no IPv6 ranges in subnet error message
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlbipv6.go
Labels: cncf-cla: yes, lgtm, size/XS, approved
