Repository kubernetes/ingress-gce, pull requests merged in 2023-01, with the labels that each got.

#1893 [Cherrypick #1890] Cherrypick metric user errors fix to release 1.20
  pkg/loadbalancers/address_manager.go
  pkg/loadbalancers/address_manager_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/test/gcehooks.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1899 Fix logs, use proper format strings argument types
  pkg/healthchecksl4/healthchecksl4.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1895 ILB: Extend the 'number_of_l4_ilbs' metric to track user errors and tre…
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/metrics/features.go
  pkg/metrics/l4metrics_test.go
  pkg/metrics/metrics.go
  pkg/metrics/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1900 [Cherrypick #1895] Cherrypick extending the number_of_l4_ilbs with us…
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/metrics/features.go
  pkg/metrics/l4metrics_test.go
  pkg/metrics/metrics.go
  pkg/metrics/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1901 Change dual-stack ILB metrics to use snake case labels
  pkg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1896 Reimplement getting load balancer source ranges
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/sourceranges.go
  pkg/utils/sourceranges_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1903 Add support for IPv6 values in loadBalancerSourceRanges
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/sourceranges.go
  pkg/utils/sourceranges_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1907 Remove using node ports for L4 NetLB RBS Services
  pkg/instancegroups/manager.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#1897 Add IsSubnetworkMissingIPv6GCEError to User Errors
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1909 Clean up error state checking
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#1884 Fix code gen process and pin dependencies for update-codegen.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-codegen.sh
Labels: cncf-cla: yes, size/L, ok-to-test

#1915 use bash for verify scripts
  hack/verify-all.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
  hack/verify-lint.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#1905 Add UserError Status to ILB DualStack metrics
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/metrics/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#1917 Cleanup node port utils GetNodePorts
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#1916 Inline dependency on legacy-cloud-providers
  pkg/annotations/gce_annotations.go
  pkg/annotations/service.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1904 NEG: Add wrappers for NEG Windows test.
  cmd/e2e-test/neg_test.go
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#1925 Update neg endpoint metrics histogram bucket
  pkg/neg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test
