Repository kubernetes/ingress-gce, pull requests merged in 2023-11, with the labels that each got.

#2300 Add L7XLBRegionalEnabled to translator and service port
  pkg/context/context.go
  pkg/controller/translator/testdata/ingress-gce-regional.json
  pkg/controller/translator/testdata/ingress-gce-regional.yaml
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/utils/serviceport.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2304 Simplify if order, no logic change, no-op change
  pkg/healthchecks/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2305 Rename get/update/delete+ILB functions to get/update/delete+Regional
  pkg/healthchecks/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2319 Rename GceL7XLBRegionalIngressClass to gce-regional-external
  pkg/annotations/ingress.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2306 Add and pass enableL7XLBRegional to NEG controller
  cmd/glbc/main.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2309 Refactor TestGetServicePort, add cmp.Diff with result ServicePort
  pkg/controller/translator/translator_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2315 Enable ServicePort NEGs for L7 RXLB
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2321 Cleanup leftover gce-regional after renaming to gce-regional-external
  pkg/controller/translator/testdata/ingress-gce-regional-external.json
  pkg/controller/translator/testdata/ingress-gce-regional-external.yaml
  pkg/controller/translator/translator_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2325 Add scope and versions for L7 RXLB
  pkg/loadbalancers/features/features.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2316 Move setting healthcheck ForNEG, ForILB to upper functions
  pkg/healthchecks/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2326 Add IsL7XLBRegional to translator
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2318 Add DefaultXLBRegionalHealthCheck for servicePorts with L7XLBRegionalEnabled
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/translator/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2324 Add creating/updating regional health checks for Ingress RXLB
  pkg/healthchecks/healthchecks.go
  pkg/translator/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2330 Add L7 Regional XLB to IsGCEIngress, depending on the flag
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2331 Add syncing default backends for L7 Regional XLB
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2333 Fix broken unit test, remove using global controller
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2320 Update composite to use contextual logging.
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/backends/syncer_test.go
  pkg/composite/gen.go
  pkg/composite/gen/main.go
  pkg/forwardingrules/forwarding_rules.go
  pkg/forwardingrules/forwarding_rules_test.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecksprovider/healthchecksprovider.go
  pkg/healthchecksprovider/healthchecksprovider_test.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4lbcommon.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/addresses.go
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/loadbalancers/l4testutils.go
  pkg/loadbalancers/l7.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/l7s_test.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/loadbalancers/target_proxies.go
  pkg/loadbalancers/url_maps.go
  pkg/neg/types/cloudprovideradapter.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#2336 Set proper features and scope for L7 Regional XLB ServicePort
  pkg/backends/features/features.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2334 Add flag to disable handling Ingress class = gce
  pkg/flags/flags.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2337 Create EXTERNAL_MANAGED backend services for Regional External Ingress
  pkg/backends/backends.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2297 Replace klog with context logging for NEG Controller
  pkg/backends/interfaces.go
  pkg/backends/neg_linker.go
  pkg/backends/neg_linker_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/poller.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/utils.go
  pkg/neg/readiness/utils_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/syncer.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/cloudprovideradapter.go
  pkg/neg/types/cloudprovideradapter_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/interfaces.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2338 Fix log to say "Regional" instead of "ILB"
  pkg/healthchecks/healthchecks.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2339 Add simple e2e creation/deletion test for gce-regional-external ingress
  cmd/e2e-test/regional_xlb_test.go
  pkg/fuzz/features/neg.go
  pkg/fuzz/gcp.go
  pkg/fuzz/helpers.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2340 Add affinity e2e test for gce-regional-external
  cmd/e2e-test/affinity_beta_test.go
  cmd/e2e-test/affinity_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2289 Hide Strong Session Affinity code behind a flag (fully)
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/backends/regional_ig_linker_test.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2342 Add App Protocol e2e tests for Ingress Regional XLB
  cmd/e2e-test/app_protocols_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2346 Disable IAP and CDN BackendConfig for Regional External Ingress
  pkg/backendconfig/validation.go
  pkg/backendconfig/validation_test.go
  pkg/controller/translator/translator.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2295 Introduce panic recovery for metrics export
  pkg/metrics/metrics.go
  pkg/servicemetrics/servicemetrics.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2345 Add e2e test that verifies CDN and IAP does not work with RXLB
  cmd/e2e-test/backend_config_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2353 Fix HTTPs to share address with HTTP for RXLB
  pkg/loadbalancers/addresses.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2350 Use same ipv6 podCIDR, and add instance2 to nodeLister.
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2360 Added missing NEG Controller Error metrics collection.
  pkg/neg/syncers/utils.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2352 Add HTTPs e2e test for Regional XLB
  cmd/e2e-test/basic_https_test.go
  pkg/loadbalancers/addresses.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2355 Add TestRegionalXLBStaticIP e2e test
  cmd/e2e-test/regional_xlb_test.go
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2357 Add TestRXLBILBShared e2e test
  cmd/e2e-test/regional_xlb_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2361 Add HTTPs redirects e2e test for RXLB Ingress
  cmd/e2e-test/redirects_test.go
  pkg/fuzz/gcp.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2362 Increase golangci-lint timeout
  .golangci.yaml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2356 Add TestRegionalXLBILBTransition e2e test
  cmd/e2e-test/regional_xlb_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2368 Rename TestRegionalXLBDraining -> TestRegionalXLBDrain
  cmd/e2e-test/draining_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2351 Add Observe to all paths of generated client API
  pkg/composite/gen.go
  pkg/composite/gen/main.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2370 Reduce e2e test polling time for Unreachable
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2369 Add backend config Logging e2e test for RegionalXLB ingress
  cmd/e2e-test/logging_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2341 New flag for degraded mode metrics collection, and add logging for the selection of endpoint calculation.
  pkg/flags/flags.go
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2373 Revert "Reduce e2e test polling time for Unreachable"
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2371 Add e2e test for BackendConfig HealthCheck for RXLB Ingress
  cmd/e2e-test/healthcheck_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2372 Fix ingKey for log message
  cmd/e2e-test/v2frontendnamer_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2375 Add more debug logs for L4 Multinetworking and L4 SSA
  pkg/backends/backends.go
  pkg/l4lb/l4lbcommon.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2378 Minor fixes and updates to logging related to multinet
  pkg/backends/backends.go
  pkg/neg/syncers/utils.go
Labels: cncf-cla: yes, lgtm, size/S, approved
