Repository kubernetes/ingress-gce, pull requests merged in 2024-01, with the labels that each got.

#2420 Revert "[Cherry pick #2359 -> 1.26] Make PublishNegControllerErrorCountMetrics run in its own goroutine"
  pkg/neg/syncers/syncer.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2421 Revert "[Cherry pick #2402 -> 1.26] Add some validations for L4 multinetwork services."
  pkg/network/network.go
  pkg/network/network_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2424 Revert "Revert "[Cherry pick #2402 -> 1.26] Add some validations for L4 multinetwork services.""
  pkg/network/network.go
  pkg/network/network_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2423 Revert "Revert "[Cherry pick #2359 -> 1.26] Make PublishNegControllerErrorCountMetrics run in its own goroutine""
  pkg/neg/syncers/syncer.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2425 Introduce new ZoneGetter and refactor related packages and tests
  cmd/glbc/main.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/regional_ig_linker_test.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils_test.go
  pkg/instancegroups/fakes.go
  pkg/instancegroups/interfaces.go
  pkg/instancegroups/manager.go
  pkg/instancegroups/manager_test.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/simple_zone_getter.go
  pkg/neg/types/simple_zone_getter_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/test/utils.go
  pkg/utils/zonegetter/fake.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved, ok-to-test

#2406 Replicate dependencies for neg usage metrics migration.
  pkg/neg/metrics/metricscollector/features.go
  pkg/neg/metrics/metricscollector/metrics.go
  pkg/neg/metrics/metricscollector/metrics_collector.go
  pkg/neg/metrics/metricscollector/metrics_collector_test.go
  pkg/neg/metrics/metricscollector/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2431 Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2429 Cherry-pick ZoneGetter change and instanceGroup fix to 1.27
  cmd/glbc/main.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/regional_ig_linker_test.go
  pkg/context/context.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/translator/translator.go
  pkg/controller/translator/translator_test.go
  pkg/controller/utils_test.go
  pkg/instancegroups/fakes.go
  pkg/instancegroups/interfaces.go
  pkg/instancegroups/manager.go
  pkg/instancegroups/manager_test.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/simple_zone_getter.go
  pkg/neg/types/simple_zone_getter_test.go
  pkg/neg/types/types.go
  pkg/neg/types/types_test.go
  pkg/test/utils.go
  pkg/utils/zonegetter/fake.go
  pkg/utils/zonegetter/node-state.md
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test

#2432 IG Manager: return the instance group name once even if it existis in…
  pkg/controller/controller_test.go
  pkg/instancegroups/manager.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2435 [Cherry pick #2431 -> 1.27] Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2308 Add contextual logging for ingress controller.
  cmd/glbc/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/loadbalancers/interfaces.go
  pkg/loadbalancers/l7s.go
  pkg/loadbalancers/loadbalancers_test.go
  pkg/sync/interfaces.go
  pkg/sync/sync.go
  pkg/utils/common/common.go
  pkg/utils/common/common_test.go
  pkg/utils/common/finalizer.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2407 Update NEG usage metrics emit.
  cmd/glbc/main.go
  pkg/metrics/features.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/types.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/metrics/metricscollector/metrics_collector.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2412 Introduce enable-ig-controller flag, and flag-gate IG controller.
  cmd/glbc/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2439 Cherry-pick Trigger node process when providerID populated to 1.27
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2434 Add more unit tests for ZoneGetter change in NEG controller
  pkg/neg/syncers/transaction_test.go
  pkg/utils/zonegetter/fake.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2438 Trigger node process when providerID populated
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2411 Introduce enable-neg-controller flag, and flag-gate NEG controller and Svcneg CRD.
  cmd/glbc/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2440 Fix Regional XLB ingress by setting Network.
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2442 Refactor runNEGController
  cmd/glbc/main.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2443 Update dependencies on 1.20
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2444 Update dependencies on 1.23
  go.mod
  go.sum
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/sys/unix/fcntl.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_bsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2445 Add more debug logging to dual stack L4 code
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2449 Remove duplicate shutdown log in NEG controller.
  pkg/neg/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2447 Create proper firewall for Regional XLB Ingress
  cmd/glbc/main.go
  pkg/firewalls/controller.go
  pkg/firewalls/controller_test.go
  pkg/loadbalancers/features/l7rxlb.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2450 Make firewall controller waits on stopCh.
  cmd/glbc/main.go
  pkg/firewalls/controller.go
  pkg/firewalls/controller_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2430 Fix log params for new klog
  pkg/neg/manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2358 Remove credential validation for IAP
  pkg/apis/backendconfig/v1/types.go
  pkg/apis/backendconfig/v1/zz_generated.openapi.go
  pkg/apis/backendconfig/v1beta1/types.go
  pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go
  pkg/backendconfig/validation_test.go
  pkg/backends/features/iap.go
  pkg/backends/features/iap_test.go
  pkg/backends/syncer.go
  pkg/metrics/features.go
  pkg/metrics/metrics_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2317 Add contextual logging L7 Health Checker.
  pkg/backends/syncer.go
  pkg/backends/syncer_test.go
  pkg/healthchecks/healthchecks.go
  pkg/healthchecks/healthchecks_test.go
  pkg/healthchecks/interfaces.go
  pkg/translator/healthchecks.go
  pkg/translator/healthchecks_test.go
  pkg/utils/healthcheck/healthcheckdesc.go
  pkg/utils/healthcheck/healthcheckdesc_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test
