Repository kubernetes/ingress-gce, pull requests merged in 2024-03, with the labels that each got.

#2472 Don't return error if ingress already do not exist
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2474 Fix broadcasting events
  pkg/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2467 Remove useless big log
  pkg/firewalls/controller.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2475 Fix VIP in params after transition
  cmd/e2e-test/regional_xlb_test.go
  pkg/fuzz/gcp.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2476 [Cherry-pick #2469 -> 1.28] Reset error state even when degraded mode is not enabled.
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2469 Reset error state even when degraded mode is not enabled.
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2477 Add context loggers to missing places
  cmd/glbc/main.go
  pkg/backends/ig_linker.go
  pkg/backends/regional_ig_linker.go
  pkg/controller/controller.go
  pkg/instancegroups/manager.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/loadbalancers/certificates.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
  pkg/sync/sync.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2471 [Cherrypick #2153, #2177, #2150 into release-1.23] Add NEG count, GCERequest and GCE Latency Metrics
  pkg/neg/controller.go
  pkg/neg/manager.go
  pkg/neg/manager_test.go
  pkg/neg/metrics/label_propagation_metrics.go
  pkg/neg/metrics/metrics.go
  pkg/neg/metrics/metrics_test.go
  pkg/neg/metrics/metricscollector/metrics.go
  pkg/neg/metrics/metricscollector/metrics_collector.go
  pkg/neg/metrics/metricscollector/metrics_collector_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/types/cloudprovideradapter.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2478 [Cherry-pick #2431 -> 1.26] Fix NEG degraded mode for L4 externalTrafficPolicy=Local services.
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2479 Add sleep after transitioning in e2e test
  cmd/e2e-test/regional_xlb_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2480 Make sure we don't create ILBs if reading legacy forwarding rule failed
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2481 Add more logs to e2e tests
  cmd/e2e-test/regional_xlb_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2486 Increase timeout and explain rxlb transition e2e test problem
  cmd/e2e-test/regional_xlb_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2487 Add validating Default 404 service in e2e tests
  pkg/fuzz/validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2485 Add back lockName to logs related to lock availability metrics.
  cmd/glbc/main.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2489 Revert "Add validating Default 404 service in e2e tests"
  pkg/fuzz/validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2491 Bump google.golang.org/protobuf version from 1.31.0 to 1.33.0 on release-1.28
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2496 Update k8s-cloud-provider to 1.27
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/gen.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/meta/compute_services.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/service.go
  vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/utils.go
  vendor/modules.txt
Labels: cncf-cla: yes, size/L, lgtm, approved

#2495 Add validating Default 404 service in e2e tests
  pkg/fuzz/default_validator_env.go
  pkg/fuzz/helpers.go
  pkg/fuzz/helpers_test.go
  pkg/fuzz/validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2498 Revert "Add validating Default 404 service in e2e tests"
  pkg/fuzz/default_validator_env.go
  pkg/fuzz/helpers.go
  pkg/fuzz/helpers_test.go
  pkg/fuzz/validator.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2433 Add support for sslPolicy for regional XLB ingress
  pkg/composite/composite.go
  pkg/loadbalancers/target_proxies.go
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2501 Update google.golang.org/protobuf v1.31.1 -> v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2500 Update google.golang.org/protobuf v1.31.1 -> v1.33.0
  go.mod
  go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/prototext/decode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/descfmt/stringer.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/defaults.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/struct_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_gen.go
  vendor/google.golang.org/protobuf/internal/impl/codec_tables.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_message.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/decode.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/encode.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/proto/merge.go
  vendor/google.golang.org/protobuf/proto/proto.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_resolve.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_validate.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protodesc/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/proto.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/type.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.proto
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2503 [release-1.28] Added user-facing log about degraded mode.
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2382 Added user-facing log about degraded mode.
  pkg/neg/syncers/transaction.go
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2507 Fix comparison for partial and full resource urls
  pkg/loadbalancers/target_proxies.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2509 Fix deleting sslPolicy by using NullFields
  pkg/composite/composite.go
  pkg/controller/controller.go
  pkg/loadbalancers/target_proxies.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2510 [Cherry-pick #2480 -> 1.28] Make sure we don't create ILBs if reading legacy forwarding rule failed
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/loadbalancers/forwarding_rules.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2505 Enhance context logging
  pkg/controller/controller.go
  pkg/firewalls/firewalls_l4.go
  pkg/healthchecksl4/healthchecksl4.go
  pkg/healthchecksl4/interfaces.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/address_manager.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlbipv6.go
  pkg/network/network.go
  pkg/utils/common/finalizer.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2504 [release-1.23] Add buckets for syncer staleness metrics
  pkg/neg/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2488 Add sawsa307 as reviewer.
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2506 Add Regional XLB Ingress sslPolicy e2e test
  cmd/e2e-test/sslpolicy_test.go
  pkg/e2e/fixtures.go
Labels: cncf-cla: yes, size/L, lgtm, approved
