Repository kubernetes/ingress-gce, pull requests merged in 2024-07, with the labels that each got.

#2599 Skip marking NEG readiness gate as ready until nodeName is set for msc, and add new error state for Node without PodCIDR
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/states.go
  pkg/neg/types/sync_errors.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2605 [Cherry-pick #2599 -> 1.30] Skip marking NEG readiness gate as ready until nodeName is set for msc, and add new error state for node without PodCIDR.
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/fakes.go
  pkg/neg/types/states.go
  pkg/neg/types/sync_errors.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2606 Replace obsolete test based on neg-status with one based on NEG CR for Standalone NEGs.
  cmd/e2e-test/upgrade/neg.go
  cmd/e2e-test/upgrade_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2582 Fix instance group sizes
  pkg/instancegroups/manager.go
  pkg/instancegroups/manager_test.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2607 Add the flag for Multi-Subnet cluster phase1 support.
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2610 Add instance group resize metrics
  pkg/instancegroups/manager.go
  pkg/instancegroups/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test
