Repository kubernetes/ingress-gce, pull requests merged in 2024-06, with the labels that each got.

#2530 Update SvcNeg CR.
  pkg/apis/svcneg/v1beta1/types.go
  pkg/apis/svcneg/v1beta1/zz_generated.openapi.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2583 Update readiness check for non-default subnet nodes.
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2584 Update Node subnet label.
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2585 Add panic recovery with error messages in L4Controller
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/metrics/metrics.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2587 ignore errors if adding a node results in "400: memberAlreadyExists"
  pkg/instancegroups/manager.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2589 Amend error handling for error "400: memberAlreadyExists"
  pkg/instancegroups/manager.go
  pkg/instancegroups/manager_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2595 [release-1.28] Upgrade to Go 1.22.4
  Makefile
  go.mod
  go.sum
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2594 [release-1.29] Update build to use Go 1.22.4
  Makefile
  go.mod
  go.sum
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2592 Build using Go 1.22.4
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2593 [release-1.30] Build using Go 1.22.4
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2591 [release-1.26] Upgrade to Go 1.22.4
  Makefile
  go.mod
  go.sum
  pkg/instancegroups/controller.go
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: cncf-cla: yes, size/L, lgtm, approved

#2590 [release-1.23] Build using Go 1.22.4
  Makefile
  go.mod
  go.sum
  pkg/instancegroups/controller.go
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2588 Remove deprecated metrics
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/servicemetrics/servicemetrics.go
  pkg/servicemetrics/servicemetrics_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved, ok-to-test
