Repository kubernetes/ingress-gce, pull requests merged in 2024-10, with the labels that each got.

#2692 Remove unused IngClassInformer and IngParamsInformer from context
  cmd/glbc/app/init.go
  cmd/glbc/main.go
  pkg/common/operator/ingress_test.go
  pkg/context/context.go
  pkg/controller/controller_test.go
  pkg/firewalls/controller_test.go
  pkg/flags/flags.go
  pkg/ingparams/client/clientset/versioned/clientset.go
  pkg/ingparams/client/clientset/versioned/doc.go
  pkg/ingparams/client/clientset/versioned/fake/clientset_generated.go
  pkg/ingparams/client/clientset/versioned/fake/doc.go
  pkg/ingparams/client/clientset/versioned/fake/register.go
  pkg/ingparams/client/clientset/versioned/scheme/doc.go
  pkg/ingparams/client/clientset/versioned/scheme/register.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/doc.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/doc.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/fake_gcpingressparams.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/fake/fake_ingparams_client.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/gcpingressparams.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/generated_expansion.go
  pkg/ingparams/client/clientset/versioned/typed/ingparams/v1beta1/ingparams_client.go
  pkg/ingparams/client/informers/externalversions/factory.go
  pkg/ingparams/client/informers/externalversions/generic.go
  pkg/ingparams/client/informers/externalversions/ingparams/interface.go
  pkg/ingparams/client/informers/externalversions/ingparams/v1beta1/gcpingressparams.go
  pkg/ingparams/client/informers/externalversions/ingparams/v1beta1/interface.go
  pkg/ingparams/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/ingparams/client/listers/ingparams/v1beta1/expansion_generated.go
  pkg/ingparams/client/listers/ingparams/v1beta1/gcpingressparams.go
  pkg/ingparams/ingparams.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2691 Add backend_type label to l4_netlbs_count and the L4_netlb latency metrics
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/metrics/metrics.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4netlb.go
  pkg/metrics/l4_metrics.go
  pkg/metrics/l4_metrics_test.go
  pkg/metrics/types.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2694 Make NodeTopologyInformer only looks for cluster-wide CR
  pkg/context/context.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2696 [Cherry-pick #2652 -> 1.31] Use default LocalityLBPolicy for ILB
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved

#2640 Add naming schema for non default subnet NEGs.
  pkg/utils/namer/l4_namer.go
  pkg/utils/namer/l4_namer_test.go
  pkg/utils/namer/namer.go
  pkg/utils/namer/namer_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2698 [Cherry-pick #2671 -> 1.29] Check PodIP against PodCIDR only when hostNetwork=false.
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2677 Trigger NEG syncers to sync on Node Topology CRD changes.
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/neg/controller.go
  pkg/neg/controller_test.go
  pkg/neg/manager.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/testing.go
  pkg/neg/utils.go
  pkg/neg/utils_test.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/fake/doc.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/fake/register.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/doc.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/fake_nodetopology.go
  vendor/github.com/GoogleCloudPlatform/gke-networking-api/client/nodetopology/clientset/versioned/typed/nodetopology/v1/fake/fake_nodetopology_client.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2699 [Cherry-pick #2671 -> 1.28] Check PodIP against PodCIDR only when hostNetwork=false.
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2682 Undesired operation detection for L4 ILB
  pkg/l4lb/l4controller.go
  pkg/l4lb/metrics/metrics.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/forwarding_rules_ipv6_test.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4ipv6.go
  pkg/loadbalancers/l4netlb.go
  pkg/loadbalancers/l4netlbipv6.go
  pkg/loadbalancers/resourceupdate.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2700 IPv6 NetLB - disallow using on standard tier network
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2689 Moving from string(zone) to endpointGroupInfo when mapping NEGs, and populate subnet values for nodes in zoneGetter and NEG syncers.
  pkg/instancegroups/manager.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/neg/manager_test.go
  pkg/neg/metrics/metricscollector/metrics_collector.go
  pkg/neg/metrics/metricscollector/metrics_collector_test.go
  pkg/neg/syncers/dualstack/migrator.go
  pkg/neg/syncers/dualstack/migrator_test.go
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/subsets.go
  pkg/neg/syncers/subsets_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_table.go
  pkg/neg/syncers/transaction_table_test.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/interfaces.go
  pkg/neg/types/types.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2707 Add multi-project CRD, add flag for multi-project CRD namespace label
  pkg/flags/flags.go
  pkg/multiproject/projectcrd/projectcrd.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2704 [Cherry-pick #2700 -> 1.31] Not ensuring NetLb when Dualstack and Network Tier forced to Standard
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/utils/utils.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2708 Fix port range to port comparison for forwarding rules
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2705 Add Shared Context for multi-project controller
  cmd/glbc/main.go
  pkg/multiproject/sharedcontext/sharedcontext.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2703 Implement namespaced informer
  pkg/multiproject/namespacedinformer/helpers.go
  pkg/multiproject/namespacedinformer/helpers_test.go
  pkg/multiproject/namespacedinformer/namespacedcache.go
  pkg/multiproject/namespacedinformer/namespacedcache_test.go
  pkg/multiproject/namespacedinformer/namespacedinformer.go
  pkg/multiproject/namespacedinformer/namespacedinformer_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2711 Update Go version to 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2713 [release-1.30] 1.30 update go 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2712 [release-1.31] Update go version to 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2714 [release-1.28] 1.28 go update 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2715 [release-1.26] Update Go Version 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2716 [release-1.23] Update Go version 1.22.8
  Makefile
  go.mod
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2720 Use Object Label to identify Project, instead of Namespace, rename the flag
  pkg/flags/flags.go
  pkg/multiproject/projectcrd/projectcrd.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2721 Rework namespacedinformer into filtering by project name
  pkg/multiproject/namespacedinformer/helpers.go
  pkg/multiproject/namespacedinformer/helpers_test.go
  pkg/multiproject/namespacedinformer/namespacedcache.go
  pkg/multiproject/namespacedinformer/namespacedcache_test.go
  pkg/multiproject/namespacedinformer/namespacedinformer.go
  pkg/multiproject/projectinformer/helpers.go
  pkg/multiproject/projectinformer/helpers_test.go
  pkg/multiproject/projectinformer/projectcache.go
  pkg/multiproject/projectinformer/projectcache_test.go
  pkg/multiproject/projectinformer/projectinformer.go
  pkg/multiproject/projectinformer/projectinformer_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2710 [Cherry-pick #2708 -> 1.31] Fix port range to port comparison for forwarding rules
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_test.go
Labels: cncf-cla: yes, size/L, lgtm, needs-ok-to-test, approved
