Repository kubernetes/ingress-gce, pull requests merged in 2025-09, with the labels that each got.

#2907 Multiproject: stop controllers when leadership ends
  cmd/glbc/main.go
  pkg/multiproject/start/start.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2979 Add more logs to multiproject start.go
  pkg/multiproject/start/start.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2980 replace 5s poll with WaitForCacheSync
  pkg/multiproject/controller/controller.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2981 Add felipeyepez to approvers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/M, approved

#2985 [Cherrypick #2970 to release-1.37] Move to independent locks for L4 and Ingress controllers.
  cmd/glbc/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2978 Let ReactionChain continue in EmulateProviderConfigLabelingWebhook
  pkg/multiproject/start/start_test.go
  pkg/multiproject/testutil/providerconfigwebhook.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2987 e2e: wait for NEG zones before returning from WaitForNegCRs
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2988 Increase NEG poll timeout to 10 mins in e2e tests
  pkg/e2e/helpers.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2990 Implement a legacy mode for the zonegetter
  pkg/context/context.go
  pkg/utils/zonegetter/README.md
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2992 Ensure Ingress CRDS only when Ingress ctrl is enabled
  cmd/glbc/main.go
  pkg/context/context.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved
