Repository kubernetes/ingress-gce, pull requests merged in 2025-06, with the labels that each got.

#2901 [Cherrypick #2882 to release-1.34] NEGController: rely on the presence of the V3 finalizer vs the RBS annotation
  pkg/neg/controller.go
  pkg/neg/controller_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2902 [Cherrypick #2880 to release-1.34] NetLB: workaround for the finalizer removal case
  pkg/l4lb/l4netlbcontroller.go
  pkg/l4lb/l4netlbcontroller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2903 NEG Controller: fix the multinet NEG location to prevent constant NEG detach calls
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2898 Fix FirewallRules unexpected patching for IPv6
  pkg/firewalls/equal.go
  pkg/firewalls/equal_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2906 Properly handle NEG readiness gate when transitioning between MSC Phase 0 and Phase 1
  pkg/neg/controller.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/readiness/utils_test.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2908 Cherry-pick #2906 -> 1.36: Properly handle NEG readiness gate when transitioning between MSC Phase 0 and Phase 1
  pkg/neg/controller.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/reflector.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/readiness/utils_test.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2909 Fix shadowing error in tests
  cmd/e2e-test/logging_test.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2912 Rephrase log message
  pkg/address/manager.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2808 Fix firewall cr creation
  pkg/firewalls/firewalls_l7_cr.go
  pkg/firewalls/firewalls_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2913 [Cherrypick #2903 -> release-1.34] NEG Controller: fix the multinet NEG location to prevent constant NEG detach calls
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, lgtm, size/M, needs-ok-to-test, approved
