Repository kubernetes/ingress-gce, pull requests merged in 2025-03, with the labels that each got.

#2823 Disable linter in hack/verify-all.sh
  hack/verify-all.sh
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2822 Change multiproject auth API to support per-provider-config token
  pkg/multiproject/gce/gce.go
  pkg/multiproject/gce/gce_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2819 Increase max number of subsets NetLB for ETP:local
  pkg/neg/syncers/subsets.go
Labels: cncf-cla: yes, lgtm, size/XS, needs-ok-to-test, approved

#2816 Garbage collect TO_BE_DELETED NEGs
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2824 Rework per-provider-config auth. Assume cluster project if no label set
  pkg/flags/flags.go
  pkg/multiproject/gce/gce.go
  pkg/multiproject/gce/gce_test.go
  pkg/multiproject/start/start_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2805 Introduce a new lock for L4 and related controllers.
  cmd/glbc/main.go
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2826 Regenerate ProviderConfig types to be Cluster scoped, not Namespace scoped
  pkg/apis/providerconfig/v1/types.go
  pkg/multiproject/controller/controller_test.go
  pkg/multiproject/finalizer/finalizer.go
  pkg/multiproject/finalizer/finalizer_test.go
  pkg/multiproject/manager/manager.go
  pkg/multiproject/start/start_test.go
  pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/fake/fake_providerconfig.go
  pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/fake/fake_providerconfig_client.go
  pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/providerconfig.go
  pkg/providerconfig/client/clientset/versioned/typed/providerconfig/v1/providerconfig_client.go
  pkg/providerconfig/client/informers/externalversions/providerconfig/v1/interface.go
  pkg/providerconfig/client/informers/externalversions/providerconfig/v1/providerconfig.go
  pkg/providerconfig/client/listers/providerconfig/v1/expansion_generated.go
  pkg/providerconfig/client/listers/providerconfig/v1/providerconfig.go
  pkg/utils/patch/patch.go
  pkg/utils/patch/patch_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2799 [Cherry-pick #2575 and #2708 -> 1.28] Forward individual ports for NetLB with 5 or less service ports
  pkg/flags/flags.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/forwarding_rules.go
  pkg/loadbalancers/forwarding_rules_ipv6.go
  pkg/loadbalancers/forwarding_rules_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, lgtm, size/XL, needs-ok-to-test, approved

#2811 script: Use instance zone instead of cluster location in setup-local script
  hack/setup-local.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2828 Add TortillaZHawaii to Reviewers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2829 Setup script for GLBC configuration on regional clusters
  hack/setup-local.sh
Labels: cncf-cla: yes, lgtm, size/M, approved, ok-to-test

#2830 Fixed setup script for zonal cluster
  hack/setup-local.sh
Labels: cncf-cla: yes, lgtm, size/S, approved, ok-to-test

#2832 Fix patching ProviderConfig resource
  pkg/utils/patch/patch.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2833 Fix linter warnings for pkg/neg/syncers
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/subsets_test.go
  pkg/neg/syncers/syncer.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2835 Improve NEG performance provision/deletion for small NetLBs
  pkg/neg/syncers/endpoints_calculator.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/subsets.go
  pkg/utils/zonegetter/fake.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2836 Fix replacing TokenBody for quoted jsons for MultiProject
  pkg/multiproject/gce/gce.go
  pkg/multiproject/gce/gce_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved
