Repository kubernetes/ingress-gce, pull requests merged in 2025-02, with the labels that each got.

#2792 Add ProviderConfig Controller
  cmd/glbc/main.go
  pkg/multiproject/controller/controller.go
  pkg/multiproject/controller/controller_test.go
  pkg/multiproject/neg/neg.go
  pkg/multiproject/sharedcontext/sharedcontext.go
  pkg/multiproject/start/start.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2804 Refactor ListSubnets
  cmd/glbc/main.go
  pkg/backends/ig_linker_test.go
  pkg/backends/integration_test.go
  pkg/backends/regional_ig_linker_test.go
  pkg/common/operator/ingress_test.go
  pkg/context/context.go
  pkg/controller/controller_test.go
  pkg/controller/utils_test.go
  pkg/firewalls/controller_test.go
  pkg/instancegroups/controller_test.go
  pkg/instancegroups/manager_test.go
  pkg/l4lb/l4controller_test.go
  pkg/l4lb/l4netlbcontroller_test.go
  pkg/loadbalancers/l4netlb_test.go
  pkg/multiproject/neg/neg.go
  pkg/neg/controller_test.go
  pkg/neg/manager_test.go
  pkg/neg/readiness/poller_test.go
  pkg/neg/readiness/reflector_test.go
  pkg/neg/readiness/utils_test.go
  pkg/neg/syncers/endpoints_calculator_test.go
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
  pkg/neg/syncers/utils.go
  pkg/neg/syncers/utils_test.go
  pkg/neg/types/types_test.go
  pkg/psc/controller_test.go
  pkg/test/gcehooks.go
  pkg/test/utils.go
  pkg/utils/zonegetter/zone_getter.go
  pkg/utils/zonegetter/zone_getter_test.go
Labels: cncf-cla: yes, lgtm, size/XXL, approved

#2807 Mark NEGs from removed subnets at TO_BE_DELETED
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2806 ProviderConfig fixes and integration test
  cmd/glbc/main.go
  pkg/flags/flags.go
  pkg/multiproject/controller/controller.go
  pkg/multiproject/gce/fake.go
  pkg/multiproject/gce/fake_test.go
  pkg/multiproject/gce/gce.go
  pkg/multiproject/manager/manager.go
  pkg/multiproject/neg/neg.go
  pkg/multiproject/start/start.go
  pkg/multiproject/start/start_test.go
  pkg/multiproject/testutil/providerconfigwebhook.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#2809 Look for correct neg when using multi-networking
  pkg/neg/syncers/transaction.go
  pkg/neg/syncers/transaction_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2813 Support generating proper GCE conf when network and subnetwork of ProviderConfig are specified using URL
  pkg/multiproject/gce/gce.go
  pkg/multiproject/gce/gce_test.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2812 Enable CR updates after NEG GC always
  pkg/neg/manager.go
  pkg/neg/manager_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved
