Repository kubernetes/ingress-gce, pull requests merged in 2025-08, with the labels that each got.

#2941 [Cherry-pick #2938 to 1.36] Reduce zone_getter log spam by adjusting log levels
  pkg/utils/zonegetter/zone_getter.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2938 Reduce zone_getter log spam by adjusting log levels
  pkg/utils/zonegetter/zone_getter.go
Labels: cncf-cla: yes, lgtm, size/M, approved

#2943 Revert "Merge pull request #2940 from panslava/release-1.34"
  pkg/utils/zonegetter/zone_getter.go
Labels: cncf-cla: yes, lgtm, size/S, needs-ok-to-test, approved

#2949 PSC Controller: avoid odd patch requests
  pkg/psc/controller.go
  pkg/psc/controller_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2955 Add Protocol Label to existing COUNT metrics
  pkg/l4lb/metrics/ipv4_metrics.go
  pkg/l4lb/metrics/ipv4_metrics_test.go
  pkg/l4lb/metrics/types.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#2961 Add --enable-l4-ipv6-only-mode flag
  pkg/flags/flags.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, ok-to-test

#2954 Prevent L4 ILB controller race conditions on service creation
  pkg/flags/flags.go
  pkg/l4lb/l4controller.go
  pkg/l4lb/l4controller_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2921 chore: Make ErrBadSvcType more descriptive about not using NEGs
  pkg/controller/errors/errors.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#2963 Remove .metadata from CRD
  pkg/crd/validation.go
  pkg/crd/validation_test.go
Labels: cncf-cla: yes, lgtm, size/S, approved

#2966 Add Rendezvous hashing for ILB weighted load balancing
  pkg/backends/backends.go
  pkg/backends/backends_test.go
  pkg/loadbalancers/l4.go
  pkg/loadbalancers/l4_test.go
  pkg/loadbalancers/l4netlb_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved, ok-to-test

#2965 [Cherry-pick #2958 to 1.36] Keep shared informers alive across ProviderConfig shutdown
  pkg/multiproject/neg/neg.go
  pkg/multiproject/start/start_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved
